### ISSUE TITLE
tailwind-config-viewer witch nuxt-bridge and ES issue

### ISSUE THREAD

**Issue by ansix** [nuxt-modules/tailwindcss#389]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@nuxtjs/tailwindcss@4.2.1` for the project I'm working on.

Description:
Import of whole directory is broken. Had to import server/index.js

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@nuxtjs/tailwindcss/dist/runtime/config-viewer.js b/node_modules/@nuxtjs/tailwindcss/dist/runtime/config-viewer.js
index d03355c..61b2192 100644
--- a/node_modules/@nuxtjs/tailwindcss/dist/runtime/config-viewer.js
+++ b/node_modules/@nuxtjs/tailwindcss/dist/runtime/config-viewer.js
@@ -1,5 +1,5 @@
 import {withoutTrailingSlash, withTrailingSlash} from "ufo";
-import createServer from "tailwind-config-viewer/server";
+import createServer from "tailwind-config-viewer/server/index.js";
 const server = createServer({
   tailwindConfigProvider: () => process.nuxt ? process.nuxt.$config.tailwind.getConfig() : {}
 }).asMiddleware();
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by Luferov** [comment]
> Facing issue with tailwind-config-viewer [tailwindcss package] when applying nuxt bridge.
> 
> <img alt="Screenshot 2021-10-15 at 3 13 18 AM" width="565" src="https://user-images.githubusercontent.com/40367136/137402689-db8228a5-cfc4-40e9-91a0-eac18ffc34b9.png">

Same issue.

**Comment by loweoj** [comment]
I just turned this off as a workaround inside nuxt.config.js:
```
tailwindcss: {
  // disable viewer with nuxt-bridge
  viewer: false,
}
```

Obviously doesn't solve the underlying issue...

**Comment by pi0** [comment]
Can you please try v5?

**Comment by pencilcheck** [comment]
Having the same issue as well with nuxt-bridge

**Comment by thierrymarianne** [comment]
Depending on `5.0.2` tag fixed a similar issue for me.
