### ISSUE TITLE
How to use this nuxt-tailwindcss with scss?

### ISSUE THREAD

**Issue by MetanoiaRichi** [nuxt-modules/tailwindcss#442]
Hello, I'm pretty new to nuxt and tailwind. How do I setup scss with nuxt-tailwindcss?
I've read something about it is recommended to use postcss but how do I setup that in my project?
Where do I import my scss files?

I'm lost and don't know how to set this up. 
I'll appreciate it if someone could point me in the right direction. Thank you!

**Comment by AntonAleikin** [comment]
Hi, to use SCSS in NUXT you simply need to install SASS & sass-loader modules as specified in nuxt docs:
https://nuxtjs.org/docs/directory-structure/assets#sass
When modules are installed - open your .vue file (e.g. page or component) and add the 'lang' attr to the <style> tag like this:
<style lang="sass">.
That's it, now you can use the SCSS syntax (as it is one of the SASS syntaxes) inside your style tag !
Simply write SCSS styles inside <style lang="sass"></style>.

If you want to write scss in a separate files - you should locate these files in the ASSETS folder in your Nuxt project.
See the docs on how to import scss files in the nuxt.config.js:
https://nuxtjs.org/docs/directory-structure/assets#styles 

In case of  Tailwind.css usage - you have to install it as specified in the nuxt-tailwind docs:
https://tailwindcss.nuxtjs.org/
and then simply use the SCSS syntax, for example, to @apply tailwind classes inside your custom class like so:
.main-button { @apply px-4  }

**Comment by ValdoGhafoor** [comment]
Hi,
I also use SCSS but can't figure out how to apply in my vue component styles
I tried

.myClass {
   @apply w-4/12;
}

And I get 

The `w-4/12,` class does not exist. If `w-4/12,` is a custom class, make sure it is defined within a `@layer` directive.

**Comment by ineshbose** [comment]
Closing this issue as it is believed to be resolved/stale now. These docs should help if required - https://tailwindcss.com/docs/using-with-preprocessors#using-sass-less-or-stylus

**Comment by LorenzoRottigni** [comment]
I don't think this issue is resolved... I have 2 projects using nuxt-tailwindcss + sass and both have errors on dev build similar to:
`The w-4/12, class does not exist. If w-4/12, is a custom class, make sure it is defined within a @layer directive.`

here's my errors:
```
[12:39:54 PM]  ERROR  Internal server error: [postcss] /home/lorenzorottigni/Documents/deesup-raas-nuxt/client/components/page/home/hero/Beta.vue?vue&type=style&index=0&scoped=79b91128&lang.sass:9:3: The d-container class does not exist. If d-container is a custom class, make sure it is defined within a @layer directive.
  Plugin: vite:css
  File: /home/lorenzorottigni/Documents/deesup-raas-nuxt/client/components/page/home/hero/Beta.vue?vue&type=style&index=0&scoped=79b91128&lang.sass:9:2
  7  |      .hero-content-outer
  8  |          @apply absolute d-container left-[50%] -translate-x-[50%] h-full
  9  |          .hero-content-inner
     |    ^
  10 |              @apply col-start-2 col-span-4 flex items-start flex-col justify-center gap-6
  11 |              h1
```

this is my tailwind.sass:
@tailwind base
@tailwind components
@tailwind utilities

@layer base
@layer components
    .d-container
        @apply container grid grid-cols-12 mx-auto
@layer utilities


imported in nuxt.config.ts using the css option:

css: ['~/assets/sass/tailwind.sass', '~/assets/sass/app.sass'],
