### ISSUE TITLE
Don't work in v5

### ISSUE THREAD

**Issue by DouglasCalora** [nuxt-modules/tailwindcss#443]
### Version
@nuxtjs/tailwindcss: v5.0.2
nuxt: 2.15.8

### What is actually happening?
I'm trying to use v5 of @nuxtjs/tailwindcss because it uses  tailwind v3, but it does not working

```js
 FATAL  Cannot find package '@nuxt/kit' imported from /home/douglas/Documents/pessoal/freela/weclix-institucional/node_modules/@nuxtjs/tailwindcss/dist/module.mjs

  at new NodeError (internal/errors.js:322:7)
  at packageResolve (internal/modules/esm/resolve.js:687:9)
  at moduleResolve (internal/modules/esm/resolve.js:728:18)
  at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:842:11)
  at Loader.resolve (internal/modules/esm/loader.js:89:40)
  at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
  at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:76:40)
  at link (internal/modules/esm/module_job.js:75:36)


   ╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                                                  │
   │   ✖ Nuxt Fatal Error                                                                                             │
   │                                                                                                                  │
   │   Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@nuxt/kit' imported from                                    │
   │   /home/douglas/Documents/pessoal/freela/weclix-institucional/node_modules/@nuxtjs/tailwindcss/dist/module.mjs   │
   │                                                                                                                  │
   ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! weclix-institucional@1.0.0 dev: `nuxt`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the weclix-institucional@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/douglas/.npm/_logs/2022-03-18T02_46_06_559Z-debug.log
```
I've tried to remove package-lock, node_modules, nothing works!
I installed v5.0.0, v5.0.1, v5.0.1. no one worked!

**Comment by sasial-dev** [comment]
v5 only supports nuxt bridge or nuxt 3.

**Comment by vencho-mdp** [comment]
Is now working?

**Comment by w3bdesign** [comment]
Seeing as Nuxt 3 is in beta, it shouldn't be necessary to have to install a beta version to be able to use version 5 of this module.

**Comment by cannap** [comment]
> v5 only supports nuxt bridge or nuxt 3.

this is not true v5 works fine for me in  "nuxt": "^2.15.8",

**Comment by pascalgermain** [comment]
I could manage to use this module with Tailwind 3 on a Nuxt 2 project, without Bridge.

- First, installed package on the right commit: https://github.com/nuxt-community/tailwindcss-module/commit/c174adb01ebe046aa243b30d957faf613ec68844

With pnpm (same with npm):
```bash
$ pnpm uninstall @nuxtjs/tailwindcss # just in case...
$ pnpm  install -D github:nuxt-community/tailwindcss-module#c174adb0
```

- Then cloned the repo separately, built it, and copied the `dist` folder in the project's `modules` directory
```bash
$ cd <another_path>
$ git clone git@github.com:nuxt-community/tailwindcss-module.git
$ cd tailwindcss-module
$ yarn
$ yarn remove postcss-nesting # was complaining about my Node version
$ yarn add postcss-nesting
$ yarn build
$ cp -R dist <path_to_project>/modules
```

- And finally replaced `@nuxtjs/tailwindcss` with `resolve(__dirname, 'modules/tailwindcss')` in Nuxt config's `buildModules`, hope this helps!

Question: would it be possible to add a new version, maybe `4.3.0`, on the commit https://github.com/nuxt-community/tailwindcss-module/commit/c174adb01ebe046aa243b30d957faf613ec68844? Would be neat :)

**Comment by pascalgermain** [comment]
Oh I forgot to say I had to rename the `.mjs` files to `.js` in the dist folder... And the cp command is `cp -R dist <path_to_project>/modules/tailwindcss`, can't edit my post anymore.

**Comment by vencho-mdp** [comment]
All that work just to get tailwind working 😒

**Comment by pascalgermain** [comment]
Yeah... That's why i asked if it's possible to create a `4.3.0` version :/

**Comment by cannap** [comment]
i installed it via yarn for "nuxt": "^2.15.8" it just worked

**Comment by pascalgermain** [comment]
> v5 only supports nuxt bridge or nuxt 3.

Well it seems to work as long as I don't use content in function format in my Tailwind config (as shown here: https://tailwindcss.nuxtjs.org/tailwind/config#merging-strategy). I get warnings in console and all my config is broken if I do so. So maybe v5 doesn't only support Nuxt bridge or Nuxt 3 after all.

**Comment by ErwinAI** [comment]
I'm having similar issues. It used to work, but somehow broke today. For me the problem was that the package "pathe" was not found for nuxt/kit. Running on nuxt 2.15.8 too.

Some information whether ^v5 of @nuxtjs/tailwindcss works for Nuxt 2 would be very welcome.

**Comment by rizalrenaldi** [comment]
Can confirm v5.0.0 is working with nuxt 2.15.8
`"nuxt": "^2.15.8"`

**Comment by pascalgermain** [comment]
I does, as long as you don't use content as a fonction ;)
