### ISSUE TITLE
使用 m-2.5 类，打包后成为 m-2\.5，导致找不到

### ISSUE THREAD

**Issue by xbf321** [nuxt-modules/tailwindcss#458]
页面用：<div class="m-2.5"></div>

实际build完之后，自动在 . 之前加了个 反斜杠 \，如下：

```
.m-2{margin:.5rem}.m-2\.5{margin:.625rem}
```

Nuxt:2.15.4
tailwind.config 配置如下：

```
const path = require('path');
module.exports = {
  mode: 'jit',
  purge: {
    enabled: true,
    content: [
      path.join(__dirname, './src/app.html'),
      path.join(__dirname, './src/**/*.vue'),
    ],
    options: {
      whitelist: ['html', 'body', 'nuxt-progress'],
    },
  },
};
```

**Comment by ineshbose** [comment]
Hi, sorry but the maintainers of this project cannot speak Chinese. If the issue is still relevant/persist in latest versions, could you create a new issue in English please?
