### ISSUE TITLE
Scale missing transform property

### ISSUE THREAD

**Issue by lacherogwu** [nuxt-modules/tailwindcss#469]
### Version
@nuxtjs/tailwindcss: 4.2.0
nuxt: 2.15.7

### Reproduction Link
https://codesandbox.io/s/frosty-forest-rohzeb?file=/pages/index.vue

### Steps to reproduce
<div class="bg-blue-500 h-96 my-20 scale-0"></div>
Add scale-0 to any div

### What is Expected?
transform: translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y));

### What is actually happening?
transform property is missing in 
.scale-0 class
and also in other scale classes

![image](https://user-images.githubusercontent.com/49835614/167132029-7b9adaa1-bef6-4294-b90f-cc6b2ef95d1b.png)

**Comment by ineshbose** [comment]
Closing this issue as it is believed to be resolved/stale now - please feel free to comment if it is still an issue in the latest version of the module.
