### ISSUE TITLE
Webpack & Yarn 3: Wrong css-loader

### ISSUE THREAD

**Issue by kolessios** [nuxt-modules/tailwindcss#472]
### Version
- `@nuxtjs/tailwindcss: ^5.0.4`
- `nuxt: 3.0.0-rc.2`
- `@nuxt/webpack-builder: ^3.0.0-rc.2`

### Reproduction Link
https://codesandbox.io/s/eloquent-nobel-bfj76l

### Steps to reproduce
- `npx nuxi init nuxt-app`
- `cd nuxt-app`
- `yarn set version stable`
- Add `nodeLinker: node-modules` to `.yarnrc.yml`
- `yarn install`
- `yarn add --dev @nuxt/webpack-builder @nuxtjs/tailwindcss`
- Add `builder: "webpack"` to `nuxt.config.ts`
- Add `modules: ["@nuxtjs/tailwindcss"]` to `nuxt.config.ts`
- `yarn dev`
- Open project url

### What is Expected?
Webpack should use `css-loader@6.7.1` and work without problems.

### What is actually happening?
Webpack uses `css-loader@5.2.7` because `@nuxtjs/tailwindcss` depends on `@nuxt/postcss8@1.1.3` creating an error.

`Terminal:`
```console
 ERROR  Failed to compile with 1 errors               friendly-errors 14:48:00


 ERROR  in ./node_modules/@nuxtjs/tailwindcss/dist/runtime/tailwind.css

Module build failed (from ./node_modules/css-loader/dist/cjs.js):
ValidationError: Invalid options object. CSS Loader has been initialized using an options object that does not match the API schema.
 - options.url should be one of these:
   boolean | function
   -> Enables/Disables 'url'/'image-set' functions handling (https://github.com/webpack-contrib/css-loader#url).
   Details:
    * options.url should be a boolean.
    * options.url should be an instance of function.
    at validate (/sandbox/node_modules/schema-utils/dist/validate.js:105:11)
    at Object.loader (/sandbox/node_modules/css-loader/dist/index.js:36:29)
                                                      friendly-errors 14:48:00
```

It can be fixed by adding the following to `package.json`:

```json
"resolutions": {
  "css-loader": "^6.7.1"
},
```

But for now you will be rewarded with #471 

### Why

`yarn why css-loader`:
```console
├─ @nuxt/postcss8@npm:1.1.3
│  └─ css-loader@npm:5.2.7 [7ee6d] (via npm:^5.0.0 [7ee6d])
│
├─ @nuxt/webpack-builder@npm:3.0.0-rc.2
│  └─ css-loader@npm:6.7.1 (via npm:^6.7.1)
│
└─ @nuxt/webpack-builder@npm:3.0.0-rc.2 [dc3fc]
   └─ css-loader@npm:6.7.1 [d5a8f] (via npm:^6.7.1 [d5a8f])
```

`yarn why @nuxt/postcss8:`
```console
└─ @nuxtjs/tailwindcss@npm:5.0.4
   └─ @nuxt/postcss8@npm:1.1.3 (via npm:^1.1.3)
```

### Notes
- I understand that it is not a high priority bug and the workaround is simple, I just make the issue to keep it in mind.

**Comment by ineshbose** [comment]
Closing this issue as it is believed to be resolved/stale now - please feel free to comment if it is still an issue in the latest version of the module.
