### ISSUE TITLE
exposeConfig with specific part is undefined

### ISSUE THREAD

**Issue by HZooly** [nuxt-modules/tailwindcss#481]
### Version
@nuxtjs/tailwindcss: **5.0.3**
nuxt: **2.15.8**

### Steps to reproduce

Set `exposeConfig` to `true` in `nuxt.config.js`
```js
export default {
  tailwindcss: {
    exposeConfig: true
  }
}
```

Import `theme` from configuration in component.
```js
import { theme } from '#tailwind-config'
```

### What is Expected?
Expecting `theme` to be defined.

### What is actually happening?
`theme` is undefined.

When importing the full configuration, I can get the `theme` field.

**Comment by gianpesto** [comment]
Same with nuxt 3 🫡

**Comment by antoineLZCH** [comment]
Hi, 

**VERSION**
```json
{
  "@nuxtjs/tailwindcss": "^5.1.3",
  "typescript": "^4.7.4"
  "nuxt": "3.0.0-rc.4",
}
```

**STEPS TO REPRODUCE**
Same steps as HZooly did :

Set `exposeConfig` to `true` in `nuxt.config.ts`.

When trying to create util method, I'm importing theme the way the doc says :

```typescript
import { theme } from '#tailwind-config'
```

I also tried with : 
```typescript
import { theme } from '~/tailwind-config'
import { theme } from '../tailwind.config.js'
```

or even :
```typescript
import resolveConfig from 'tailwindcss/resolveConfig';
import tailwindConfig from '../../../tailwind.config.js';

const fullConfig = resolveConfig(tailwindConfig)
```

Finally, I tried with installing `@types/tailwindcss` and doing this way :

```typescript
import { TailwindConfig } from 'tailwindcss/tailwind-config';
import resolveConfig from 'tailwindcss/resolveConfig'
import tailwindConfig from '../tailwind.config.js'

const fullConfig = resolveConfig(tailwindConfig as unknown as TailwindConfig)
```

Then got this error on runtime :

```shell
TS2307: Cannot find module '#tailwind-config' or its corresponding type declarations.
```

or on devtools console : 
```shell
Uncaught (in promise) SyntaxError: The requested module '/_nuxt/tailwind.config.js' does not provide an export named 'default' (at colors.ts:2:1)
```


I don't know if I'm doing this the wrong way but it seems I'm not alone with this issue.

**Comment by hacknug** [comment]
The only way to make this work currently is to import the fully resolved config like this:

```js

**Comment by ineshbose** [comment]
The method above doesn't allow tree-shaking unfortunately - I hope a fix is made soon!

**Comment by rikzwarthoff** [comment]
Any progress on this?

**Comment by ineshbose** [comment]
I think the issue may be somewhere here? https://github.com/nuxt-modules/tailwindcss/blob/4781e6d3f5453237879c81c74ca08ce92be9b6e1/src/module.ts#L151

I don't see a `tailwind.config.mjs` generated in my `.nuxt` directory. Could investigate for a PR.
