### ISSUE TITLE
 Tailwind 4.2.1 -> 5.1.3 = FATAL  Invalid host defined options

### ISSUE THREAD

**Issue by sebalaini** [nuxt-modules/tailwindcss#497]
### Version
@nuxtjs/tailwindcss: 5.1.3
nuxt: 2.15.8
node: 16.13

### Steps to reproduce
When upgrading from V4 to V5 there is a fatal error `Invalid host defined options`
<img width="665" alt="image" src="https://user-images.githubusercontent.com/17096352/178119381-b5726ad4-9a4c-49ff-b2be-1495818629e7.png">

I've done this upgrade on another project with yarn and I didn't have any issue but with npm I have this.

These are all my dependencies
```
  "dependencies": {
    "@nuxt/babel-preset-app": "^2.15.8",
    "@nuxtjs/axios": "^5.13.6",
    "core-js": "^3.23.4",
    "js-cookie": "^3.0.1",
    "nuxt": "^2.15.8",
    "nuxt-fontawesome": "^0.4.0",
    "vuedraggable": "^2.24.3"
  },
  "devDependencies": {
    "@babel/eslint-parser": "^7.18.2",
    "@fortawesome/fontawesome-svg-core": "^6.1.1",
    "@fortawesome/free-regular-svg-icons": "^6.1.1",
    "@fortawesome/free-solid-svg-icons": "^6.1.1",
    "@fortawesome/vue-fontawesome": "^2.0.8",
    "@nuxtjs/dotenv": "^1.4.1",
    "@nuxtjs/eslint-config": "^10.0.0",
    "@nuxtjs/eslint-module": "^3.1.0",
    "@nuxtjs/storybook": "^4.3.2",
    "@nuxtjs/style-resources": "^1.2.1",
    "@nuxtjs/tailwindcss": "^4.2.1",
    "@vue/test-utils": "^1.2.2",
    "babel-core": "7.0.0-bridge.0",
    "eslint": "^8.19.0",
    "eslint-plugin-nuxt": "^3.2.0",
    "jest": "26.6.3",
    "plop": "^3.1.1",
    "postcss": "^8.4.14",
    "postcss-html": "^1.5.0",
    "sass": "^1.53.0",
    "sass-loader": "10.1.1",
    "style-loader": "^3.3.1",
    "stylelint": "^14.9.1",
    "stylelint-config-recommended": "^8.0.0",
    "stylelint-config-standard-scss": "^4.0.0",
    "stylelint-declaration-strict-value": "^1.8.0",
    "vue-jest": "^3.0.7",
    "vue-loader": "15.9.8",
    "webpack": "4.46.0"
  }
```

**Comment by othy54** [comment]
Same here ...

**Comment by taksugit** [comment]
This is similar to this(https://github.com/nuxt/bridge/issues/266#issuecomment-1098195943)

It does work by adding `DISABLE_V8_COMPILE_CACHE=true`
However, It doesn't work by recreating yarn.lock 😕

**Comment by em-piguet** [comment]
rebuilding after removing "node_modules" + yarn.lock + .nuxt/  works for me with "@nuxtjs/tailwindcss": "^5.3.2",

**Comment by sebalaini** [comment]
I finally switched to yarn and deleted .nuxt + nod_modules and seems to work now, though a lot of styles seem to be broken even though I don't use deprecated classes 🤷‍♂️

**Comment by derHodrig** [comment]
Does anyone know how this issue works, when it comes? Im on v6.1.3 and nuxt v2.15.3 and the problem came back. (using default settings)

**Comment by aliwesome** [comment]
@derHodrig did you fix this issue?

**Comment by derHodrig** [comment]
@aliwesome currently I use nuxt 2.16.3 and nuxt/tailwind 6.6.6 with YARN2 nodelinker and currently I have no issues.
