### ISSUE TITLE
Tailwind content parsing breaks the module

### ISSUE THREAD

**Issue by kpdemetriou** [nuxt-modules/tailwindcss#504]
### Steps to reproduce

Set `content` in `tailwind.config.js` to a non-array as described [in the Tailwind docs](https://tailwindcss.com/docs/content-configuration#transforming-source-files).

### What is Expected?

The absence of errors.

### What is actually happening?

`Cannot start nuxt:  (tailwindConfig.content || []).map is not a function`.

### Additional Commentary

You cannot assume that `tailwindConfig.content` is an array. It can also be an object. In the event that `tailwindConfig.content` is an object, you want to derive the list of files from `tailwindConfig.content.files`.

**Comment by ineshbose** [comment]
Let's track this in #671
