### ISSUE TITLE
@tailwindcss/forms not working with @nuxtjs/tailwindcss:^5.1.2

### ISSUE THREAD

**Issue by DenysPoliarush** [nuxt-modules/tailwindcss#506]
### Version
@nuxtjs/tailwindcss: 5.1.2
nuxt: 2.15.5

### What is Expected?
reset for input styles provided by this plugin, like this
<img width="533" alt="Screenshot 2022-07-14 at 17 08 29" src="https://user-images.githubusercontent.com/66991536/179002124-657b7a5a-19a1-4774-ac32-2ef42475e4e7.png">

### What is actually happening?
Nothing, these styles do not exist

This worked fine with version 4.1.1, but after upgrading to version 5.1.2 it no longer works

**Comment by Atinux** [comment]
Can you please provide a reproduction and re-open the issue?
