### ISSUE TITLE
Broken changelog page in prod

### ISSUE THREAD

**Issue by hacknug** [nuxt-modules/tailwindcss#509]
### Reproduction Link

https://tailwindcss.nuxtjs.org/community/changelog/

### Steps to reproduce
Enter the provided link. You'll see a bunch of error from `@nuxt/content` complaining about the component not using slots. This works fine during development.

### What is Expected?
The page should render in production the same way it does during development.

### What is actually happening?
The `ContentRenderer` component is complaining because apparently it is not being used properly. This issue is probably coming from `@docus/docs-theme` or `@docus/github` since I'm assuming you have a base component to render changelogs in all of the module websites.

**Comment by Rosendito** [comment]
ponganse a laburar
