### ISSUE TITLE
installing nuxtjs/tailwindcss on nuxt 3 rc6 introduces warnings for nuxt/postcss8

### ISSUE THREAD

**Issue by AliQ80** [nuxt-modules/tailwindcss#513]
### Version
@nuxtjs/tailwindcss: 5.3.0
nuxt: 3.0.0-rc.6

### Steps to reproduce
install nuxt 3

npx nuxi init nuxt-app
yarn install
yarn dev -o

at this step I get the warning => install nuxt/tailwind module

yarn add -D @nuxtjs/tailwind

### What is Expected?
no warning messages

### What is actually happening?
got these warning messages

warning "@nuxtjs/tailwindcss > @nuxt/postcss8 > css-loader@5.2.7" has unmet peer dependency "webpack@^4.27.0 || ^5.0.0".
warning "@nuxtjs/tailwindcss > @nuxt/postcss8 > postcss-loader@4.3.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".

### Thoughts
to my understanding @nuxt/postcss8 only supports nuxt 2, and nuxt 3 uses vite by default
so that my be the issue but I'm not sure

is there a fix for this warning

thank you

**Comment by Atinux** [comment]
I think we can remove `@nuxt/postcss8` from dependencies and ask the user to install it if using Nuxt 2, WDYT @pi0 ?

**Comment by kotx** [comment]
I also still have this issue. Is it possible for this to be fixed @pi0?

**Comment by Atinux** [comment]
Could you please upgrade to latest Nuxt 3 please?

**Comment by kotx** [comment]
That seems to have fixed the issue, thanks

**Comment by ineshbose** [comment]
@mschoeffmann if you can give a reproduction, we can investigate!

**Comment by ineshbose** [comment]
Thanks, I can confirm this issue. (link to `@nuxt/postcss8` - https://github.com/nuxt/postcss8, https://www.npmjs.com/package/@nuxt/postcss8)

**Comment by NarHakobyan** [comment]
You closed this without fixing :/

**Comment by ineshbose** [comment]
Thanks. Will be removing `@nuxt/postcss8` from dependencies.
