### ISSUE TITLE
Raw content in the content option throws an error

### ISSUE THREAD

**Issue by nathan-hubelia** [nuxt-modules/tailwindcss#518]
### Version
@nuxtjs/tailwindcss: v5.3.1
nuxt: v2.15.8 

### Reproduction Link
https://codesandbox.io/s/nuxtjs-tailwindcss-content-raw-x4iny3?file=/nuxt.config.js

### Steps to reproduce
Add raw content to the content option of the tailwind config. (https://tailwindcss.com/docs/content-configuration#configuring-raw-content)

### What is Expected?
Raw content in the content option shouldn't throw an error as it's something that's supported in the official tailwind documentation.

### What is actually happening?
The project cannot compile anymore as the module attempts to parse the raw content object as a string path.

**Comment by Atinux** [comment]
Sorry for the late answer, can you confirm with latest version of Nuxt & Tailwind module?

**Comment by Atinux** [comment]
Feel free to re-open if still an issue
