### ISSUE TITLE
`content` property required in config

### ISSUE THREAD

**Issue by talaxasy** [nuxt-modules/tailwindcss#519]
### Version
@nuxtjs/tailwindcss: ^5.3.1
nuxt: 3.0.0-rc.6

### Bug description
When I try to connect plugin called **aspectRatio** into the nuxt.config --> tailwindcss --> config --> pligins I get an error

### What is Expected?
I successfully connect my plugin

### What is actually happening?
```
Type '{ plugins: any[]; }' is not assignable to type 'Config'.
  Property 'content' is missing in type '{ plugins: any[]; }' but required in type 'RequiredConfig'.
```

![error 1_1](https://user-images.githubusercontent.com/25802675/184809364-8792af0b-8513-4225-9155-d507ebfc916e.png)
![error 1_2](https://user-images.githubusercontent.com/25802675/184809365-c79be3b7-3da5-427c-aab3-10712044681a.png)

**Comment by dzcpy** [comment]
Same issue. Any ideas?

**Comment by dzcpy** [comment]
It seems that you'll have to specify `content` attribute in the config

**Comment by ineshbose** [comment]
Closing this issue as it is believed to be resolved/stale now - please feel free to comment if it is still an issue in the latest version of the module.

**Comment by jonorozcoc** [comment]
![image](https://github.com/nuxt-modules/tailwindcss/assets/8442497/f7bc85b1-cd41-43d7-b00c-d11d17a1608b)

Using the latest version and still persists

![image](https://github.com/nuxt-modules/tailwindcss/assets/8442497/4a928c03-80aa-4c6c-835e-8c4d034900d6)

**Comment by talaxasy** [comment]
@jonorozcoc yes, but let them know it should be noted in docs

**Comment by jonorozcoc** [comment]
@talaxasy, if that's the ideal scenario, yes, it should be included in the docs. But, as I only want to update the plugins key, why should I include the content key? That's what I mean with that being an unexpected behavior
