### ISSUE TITLE
Does not work with nuxt/content

### ISSUE THREAD

**Issue by devotoare** [nuxt-modules/tailwindcss#520]
### Version
@nuxtjs/tailwindcss: 5.3.2
nuxt: 3.0.0-rc.8

### Reproduction Link
https://github.com/devotoare/nuxt-tailwind-content-bug

### Steps to reproduce
Follow instructions on: https://tailwindcss.nuxtjs.org/examples/content

### What is Expected?
Classes work.

### What is actually happening?
If the class is not present in other parts of the code the class in content gets ignored.

**Comment by mahapo** [comment]
I think is the same issue like here #515

**Comment by Barbapapazes** [comment]
Now reload full page when using content driven mode ! (rc-11 and content 2.1.1)

**Comment by ineshbose** [comment]
Closing this issue as it is believed to be resolved/stale now - please feel free to comment if it is still an issue in the latest version of the module.
