### ISSUE TITLE
example to use with Ant desing vue

### ISSUE THREAD

**Issue by rimsila** [nuxt-modules/tailwindcss#525]
I have use [Andv](http://antdv.com/) with @nuxtjs/tailwindcss but Antd always override  tw class.
here is my config https://github.com/next-dev-team/nuxt3-ant-design/blob/main/nuxt.config.ts

**Comment by ineshbose** [comment]
Question could do with a bit more context, but I'm also guessing it's outdated. If you have an answer, please feel free to put it down here, otherwise I would suggest that the styling could be added in `nuxt.options.css` or in `tailwind.css` with components glob in `tailwindcss.config.content`.
