### ISSUE TITLE
Option to remove logging of tailwind CSS location

### ISSUE THREAD

**Issue by JohnCampionJr** [nuxt-modules/tailwindcss#527]
### Is your feature request related to a problem? Please describe.
No

### Describe the solution you'd like
An ability to set an option to disable the console logging of the tailwind.css location.

### Describe alternatives you've considered
If not an option, then maybe only log outside production environments?

### Additional context
Like to minimize console output during build so I can identify actual problems.

**Comment by ineshbose** [comment]
Closing this issue as it is believed to be resolved/stale now - please feel free to comment if it is still an issue in the latest version of the module.

**Comment by JohnCampionJr** [comment]
This is actually still an issue.  Don't really need to see this on prod/CI environments

**Comment by ineshbose** [comment]
Do you think this could be a Nuxt feature? The module only really uses the kit utilities' logger. Just adding this check may not be intuitive, and some may want to keep the log message to ensure what files are being used in the build.

**Comment by JohnCampionJr** [comment]
Well, that could be part of a larger conversation. :)  I'd love a Nuxt option to only show errors and warnings outside of the core nuxt info, but maybe that's just me.

**Comment by JohnCampionJr** [comment]
I just checked the logger provided by nuxt/kit.  It is simply a reference to consola:

https://github.com/nuxt/nuxt/blob/main/packages/kit/src/logger.ts

Would you take a PR if I add a `quiet` option?  Would default to false as to be a non-breaking change.

**Comment by ineshbose** [comment]
Please 🙂

**Comment by ineshbose** [comment]
Hi, sorry this has been stale for a while - I thought I had mentioned this - do you think we can make use of [CONSOLA_LEVEL](https://github.com/unjs/consola#log-level) for this instead? Could set as environment variable before build and try values 2 or 1.

**Comment by jpsc** [comment]
@ineshbose I've [recreated a PR](https://github.com/nuxt-modules/tailwindcss/pull/732) for this issue based on his work + feedback.

**Comment by Redskinsjo** [comment]
This issue is relevant to me, as it is populating the terminal and it is useless.

**Comment by ineshbose** [comment]
Lately, this log has been on my mind too and I'm thinking too it should be removed from build logs. Let me see if I do it as part of #798 or a separate commit.
