### ISSUE TITLE
Incorrect formatting and no highlighting

### ISSUE THREAD

**Issue by talaxasy** [nuxt-modules/tailwindcss#530]
How to make Volar correctly format postcss syntax and highlight it?
![image](https://user-images.githubusercontent.com/25802675/188527729-4201a3e8-b154-475e-8139-e996e0879f6d.png)

### Version
@nuxtjs/tailwindcss: 5.3.1
nuxt: 3.0.0-rc.8

**Comment by talaxasy** [comment]
OK, I installed a Prettier extension for VScode and it normalized the formatting, but the Highlight problem remains.

**Comment by Atinux** [comment]
You need to install this postcss extension https://marketplace.visualstudio.com/items?itemName=cpylua.language-postcss
