### ISSUE TITLE
Unknown error from PostCSS plugin. Your current PostCSS version is 8.4.14, but postcss-custom-properties uses 7.0.39

### ISSUE THREAD

**Issue by gerbenvandijk** [nuxt-modules/tailwindcss#534]
### Version
@nuxtjs/tailwindcss: 5.3.3
nuxt: 2.15.8

### Steps to reproduce
When upgrading from 5.3.2 to 5.3.3 on Nuxt 2.15.8, i'm getting the error as displayed below at Nuxt build time.

### What is expected
The Nuxt build  to continue to work without any build errors.

### What is actually happening?

I'm getting the following build error: `Unknown error from PostCSS plugin. Your current PostCSS version is 8.4.14, but postcss-custom-properties uses 7.0.39`

### My solution
Upon further investigation I noticed that the upgrade of @nuxtjs/tailwindcss contains a version bump of postcss-custom-properties (^12.1.7 to ^12.1.8). Adding 12.1.7 of postcss-custom-properties as a dependancy of my project resolved the error above.

**Comment by dohahelmy** [comment]
I got the exact same issue with different version of tailwindcss 
![image](https://user-images.githubusercontent.com/17557397/197052654-84993027-29f6-4300-afa2-f8c14bbb5403.png)
If I added post-custom-properties as shown, it should help?

**Comment by ineshbose** [comment]
Closing this issue as it is believed to be resolved/stale now - please feel free to comment if it is still an issue in the latest version of the module.
