### ISSUE TITLE
Cannot start nuxt:  (tailwindConfig.content || []) is not iterable

### ISSUE THREAD

**Issue by Icesofty** [nuxt-modules/tailwindcss#541]
### Version
@nuxtjs/tailwindcss": "^5.3.5
 nuxt: 3.0.0-rc.11

### Reproduction Link
https://stackblitz.com/edit/nuxt-framework-dubths?file=nuxt.config.ts

### Steps to reproduce
`yarn dev`

### What is Expected?
https://tailwindcss.com/docs/content-configuration#transforming-source-files

I want to use the `content.transform` option to transform .md files from the /content/ folder to format and compiles it into HTML before scanning it for class names. 

### What is actually happening?
It looks like the module is excepting an Array instead of an Object, got an error : 
`Cannot start nuxt:  (tailwindConfig.content || []) is not iterable`

**Comment by Atinux** [comment]
> I want to use the content.transform option to transform .md files from the /content/ folder to format and compiles it into HTML before scanning it for class names.

You don't have to do this, Nuxt Content already tell Tailwind to scan the `content/` directly and it works.
