### ISSUE TITLE
Option to off auto inject to global css

### ISSUE THREAD

**Issue by younho9** [nuxt-modules/tailwindcss#543]
### Is your feature request related to a problem? Please describe.

No.

### Describe the solution you'd like

An ability to set an option to disable auto inject to global css. 

### Describe alternatives you've considered

If not an option, then could I inject css to only specific layouts or pages?

### Additional context

> #### injectPosition
>
> This option lets you adjust the position of the [global CSS](https://v3.nuxtjs.org/api/configuration/nuxt.config#css) injection, which affects the CSS priority. You can use multiple formats to define the position:
> 
> https://tailwindcss.nuxtjs.org/getting-started/options#injectposition

**Comment by Atinux** [comment]
Feel free to open a PR to add the option to set `cssPath` to `false`
