### ISSUE TITLE
Add `content` folder to tailwind paths by default

### ISSUE THREAD

**Issue by manniL** [nuxt-modules/tailwindcss#547]
### Is your feature request related to a problem? Please describe.

When using `@nuxt/content`, the `content/` folder will not be checked by Tailwind's JIT engine by default.

### Describe the solution you'd like

That it will be checked and classes will be generated

### Describe alternatives you've considered

Adding it manually which is error-prone 🙈

**Comment by Atinux** [comment]
Actually it should be added by default, you can test with running `yarn dev` @manniL 

See https://github.com/nuxt/content/blob/005fdfd19aa9658f821cb64a868d7f4d09582e1f/src/module.ts#L594-L597

**Comment by manniL** [comment]
Interesting! I'll have a deeper look once again and report back ☺️

**Comment by manniL** [comment]
Yes, my bad! The project still had tailwindcss as *buildModule* causing behavior.
Maybe a warning for Nuxt3 users who accidentially use `buildModules` would make sense here?

**Comment by Atinux** [comment]
Don't you have the TS warning?
![CleanShot 2022-10-19 at 15.56.28@2x.png](https://volta.s3.fr-par.scw.cloud/Clean_Shot_2022_10_19_at_15_56_28_2x_3a060abd57.png)
