### ISSUE TITLE
How to get tailwind working across modules within a NX workspace?

### ISSUE THREAD

**Issue by mklueh** [nuxt-modules/tailwindcss#558]
I'm trying to get tailwind working for my ux library module as well, but so far only components of the actual application are processed.

At first I was relying on "createGlobPatternsForDependencies", but this always returns an empty array for whatever reason.
So I also tried to reference the library module directly, but this also won't work.

This is my tailwind.config.js
```
const {createGlobPatternsForDependencies} = require('@nrwl/react/tailwind');
const {join} = require('path')
module.exports = {
  content: [
    join(__dirname, 'src/**/*!(*.stories|*.spec).{ts,tsx,html,js,jsx,ts,tsx,vue}'),

    // returns empty array
    ...createGlobPatternsForDependencies(__dirname),
 
    // direct reference has no effect either
    `./libs/general/base/src/molecules/*.{vue,js}`,

    `components/**/*.{vue,js}`,
    `layouts/**/*.vue`,
    `pages/**/*.vue`,
    `composables/**/*.{js,ts}`,
    `plugins/**/*.{js,ts}`,
    `App.{js,ts,vue}`,
    `app.{js,ts,vue}`
  ],
```

What am I missing to get it working for the library module as well?

**Comment by this-gavagai** [comment]
I'm facing this issue with a Vue plugin. For what it's worth, I had this same problem when installing tailwind manually too, so I don't think it's specific to this module.

I was able to get it to work by adding the path to my tailwindcss.config.ts file's content attribute:
```javascript
`content: [
    './node_modules/MODULE_NAME/**/*.vue'
 ],
```

This is inefficient and inelegant, however, so I hope a better way is possible.
