### ISSUE TITLE
Big CLS with .scss files

### ISSUE THREAD

**Issue by waysagency** [nuxt-modules/tailwindcss#559]
### Version
@nuxtjs/tailwindcss: "^6.1.3"
nuxt: "3.0.0-rc.12"

### What is Expected?
The css should be printed directly in the DOM.

### What is actually happening?
The css is renderd in a .css file.

What normally happens without any configuration is that the css is printed into the DOM and imported as a css file.
![image](https://user-images.githubusercontent.com/76130749/200415429-d25d46a7-aea1-47cb-9174-ca751e874e33.png)

Now when I use SASS and add this to the configuration, the CSS is not printed to the DOM. This causes huge CLS and weird behavior.
![image](https://user-images.githubusercontent.com/76130749/200415660-1ab966ca-2f73-4280-88eb-51af357300fb.png)

Can someone explain why this is happening and how I can get the CSS printed to the DOM?

Thanks!!

**Comment by waysagency** [comment]
I just found out that the problem is on the side of Nuxt... css will be printed in the DOM within a style tag. And scss not...

**Comment by ineshbose** [comment]
It's a decision from the framework to exclude the CSS to have HTML DOM to be of smaller size.
You can read more in #579 and https://github.com/nuxt-modules/tailwindcss/issues/531#issuecomment-1277539649
