### ISSUE TITLE
Typography plugin is being ignored

### ISSUE THREAD

**Issue by wrench1815** [nuxt-modules/tailwindcss#565]
### Version
@nuxtjs/tailwindcss:  v6.1.3
nuxt:  v3.0.0-rc.13

### Steps to reproduce

https://github.com/wrench1815/tail_ext_repro

```bash
yarn postinstall
```

### What is Expected?

`@tailwindcss/typography` plugin being included in compiled `tailwind.config.cjs`

### What is actually happening?
`@tailwindcss/typography` plugin is not included in compiled `tailwind.config.cjs`. Instead it shows null there.

```js
"plugins": [
  null,
  {
    "config": {
      "theme": {
        "extend": {
          "colors": {
            "transparent": "transparent",
            "current": "currentColor"
          }
        }
      }
    }
  }
],
```

**Comment by nuraeil** [comment]
Same goes for the Forms plugin. It is also not being included. Aspect-Ratio and Line-Clamp are working just fine.

```cjs
  "plugins": [
    null,
    null,
    {
      "config": {
        "theme": {
          "lineClamp": {
            "1": "1",
            "2": "2",
            "3": "3",
            "4": "4",
            "5": "5",
            "6": "6"
          }
        },
        "variants": {
          "lineClamp": [
            "responsive"
          ]
        }
      }
    },
```

**Comment by te1** [comment]
Same problem here. As mentioned in https://github.com/tailwindlabs/tailwindcss-intellisense/issues/663#issuecomment-1314915199 this also breaks tailwindcss-intellisense in VS Code.

As a workaround I manually deleted the `"plugins": [null]` part in `.nuxt/tailwind.config.cjs` but that also means no intellisense for those plugins.

**Comment by wrench1815** [comment]
Yep I've seen it affect only intellisense but only on latest 2 versions Of extension, If I use v0.8.7 of extension intellisense is working. Also, the Styles are being applied from `@tailwindcss/typography` without any problem in both dev and prod.

**Comment by jjzhang1996** [comment]
At least for @tailwind/forms you have to call the package so that it works. 
Try 

import tailwindForms from '@tailwindcss/forms';
import tailwindTypography from '@tailwindcss/typography'

export default defineNuxtConfig({
    modules: [
        '@nuxtjs/tailwindcss',
    ],
    tailwindcss: {      
      config: {
        plugins: [
            tailwindForms({strategy: 'base'}),
            tailwindTypography({class: 'prose'})
        ]
      }
    }
})

**Comment by ineshbose** [comment]
`tailwind.config.cjs` is no longer being generated as Tailwind CSS v3.3 supports reading ESM/TS configuration.
Now you can still generate a CJS if you'd like (https://tailwindcss.nuxtjs.org/tailwind/editor-support), but plugins would still not be added to it as they cannot be serialized by Nuxt to be written into a file. So, the solution would be to move the configuration out from `nuxt.options.tailwindcss.config` to a separate `tailwind.config` file. 🙂
