### ISSUE TITLE
VS code Intellisense support is not working

### ISSUE THREAD

**Issue by lagamura** [nuxt-modules/tailwindcss#567]
Description: Intellisense support is not working

### Version
@nuxtjs/tailwindcss: ex: v6.1.3
nuxt: v3.0.0-rc.13

### Reproduction Link
Fork this repository: https://github.com/lagamura/nuxt-app-tailwind-module
and run `npm install`

### Steps to reproduce
1. install nuxt 3 rc by `npx nuxi init nuxt-app`
2. run `npm install --save-dev @nuxtjs/tailwindcss` and follow the [setup instructions](https://tailwindcss.nuxt.dev/getting-started/setup)
3. run `npm install`
4. install tailwindcss extension in vs code
5. follow the instructions in [docs](https://tailwindcss.nuxt.dev/tailwind/editor-support) to activate intellisense

### What is Expected?

IDE intellisense support, autocomplete, hover etc.

### What is actually happening?

Editor support not working, although if I add the `tailwind.config.js` file in the directory it works fine, but this may create a conflict between `.nuxt/tailwind.config.cjs` file.

**Comment by DDiran** [comment]
Same here! Followed the steps above and got the following error:

```
[.nuxt/tailwind.config.cjs] Building...
[Error - 09:59:35] Tailwind CSS: Cannot read properties of null (reading '__isOptionsFunction')
TypeError: Cannot read properties of null (reading '__isOptionsFunction')
    at /Users/MyUsername/.vscode/extensions/bradlc.vscode-tailwindcss-0.9.1/dist/tailwindServer.js:712:9720
    at Array.map (<anonymous>)
    at /Users/MyUsername/.vscode/extensions/bradlc.vscode-tailwindcss-0.9.1/dist/tailwindServer.js:712:9705
    at _require.Ks.default.require (/Users/MyUsername/.vscode/extensions/bradlc.vscode-tailwindcss-0.9.1/dist/tailwindServer.js:178:45097)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /Users/MyUsername/.vscode/extensions/bradlc.vscode-tailwindcss-0.9.1/dist/tailwindServer.js:712:10084
    at Generator.next (<anonymous>)
    at /Users/MyUsername/.vscode/extensions/bradlc.vscode-tailwindcss-0.9.1/dist/tailwindServer.js:1:1219
    at new Promise (<anonymous>)
    at Xt (/Users/MyUsername/.vscode/extensions/bradlc.vscode-tailwindcss-0.9.1/dist/tailwindServer.js:1:1039)
```

**Comment by xiBread** [comment]
This is because the generated `plugins` array in `.nuxt/tailwind.config.cjs` becomes `[null]` if you have any plugins for some reason. Current workaround is to use the `tailwindcss:config` hook.

```ts
// nuxt.config.ts
import type { Config } from "tailwindcss";

export default defineConfig({
	hooks: {
		"tailwindcss:config": (config: Config) => {
			config.plugins?.push(...);
		}
	}
})
```

This won't provide IntelliSense for any plugins, but it will have everything else.

**Comment by ExEr7um** [comment]
Related: #565

**Comment by abbadanor** [comment]
https://github.com/nuxt-modules/tailwindcss/issues/567#issuecomment-1317996722 did not work for me. This did:
```javascript
// nuxt.config.ts
import tailwindForms from '@tailwindcss/forms'
export default defineNuxtConfig({
    tailwindcss: {
        config: {
            plugins: [
                tailwindForms({ strategy: 'base' })
            ]
        }
    }
})
```

**Comment by tberk** [comment]
Changing the import style fixed for me.

```
// tailwind.config.js
// changed this
import defaultTheme from 'tailwindcss/defaultTheme'

// to this
const defaultTheme = `require('tailwindcss/defaultTheme')
```

**Comment by ineshbose** [comment]
This should no longer be an issue, and you can disregard `.nuxt/tailwind.config.cjs` now. Please upgrade to 6.6.8 (with Tailwind CSS v3.3), and read https://tailwindcss.nuxtjs.org/tailwind/editor-support. If issue still persists, please do comment here and I'll reopen.
