### ISSUE TITLE
On https://nuxt.com/modules/tailwindcss text is too dark

### ISSUE THREAD

**Issue by jeremycoder** [nuxt-modules/tailwindcss#571]
### Version
@nuxtjs/tailwindcss: 
nuxt: 

### Steps to reproduce
Go to https://nuxt.com/modules/tailwindcss and look at the Quick Step area. The text is too dark to read.

### What is Expected?
The text should be easy to read.

### What is actually happening?
The text is too dark to read.

**Comment by Atinux** [comment]
Thank you, we need to improve the syntax highlight for light mode.

**Comment by Atinux** [comment]
It's now fixed: https://nuxt.com/modules/tailwindcss

**Comment by jeremycoder** [comment]
Awesome! Thank you! Love you guys! God bless you!
