### ISSUE TITLE
Cannot destructure property 'nuxt' of 'this' as it is undefined.

### ISSUE THREAD

**Issue by PawFV** [nuxt-modules/tailwindcss#572]
### Version
@nuxtjs/tailwindcss: 5.3.3
nuxt: 2.15.8
platform: Windows 11.

### Reproduction Link
https://github.com/PawFV/platform-portal

### Steps to reproduce
`yarn install && yarn dev`

### What is Expected?
Project should start in development mode

### What is actually happening?
```
 FATAL  Cannot destructure property 'nuxt' of 'this' as it is undefined.                                                        11:14:20  

  at postcss8Module (node_modules\@nuxt\postcss8\dist\index.js:16:10)
  at installModule (/C:/Users/paujo/platform-portal/node_modules/@nuxt/kit/dist/index.mjs:416:9)
  at async setup (/C:/Users/paujo/platform-portal/node_modules/@nuxtjs/tailwindcss/dist/module.mjs:186:7)
  at async ModuleContainer.normalizedModule (/C:/Users/paujo/platform-portal/node_modules/@nuxt/kit/dist/index.mjs:167:5)
  at async ModuleContainer.addModule (node_modules\@nuxt\core\dist\core.js:239:20)
  at async ModuleContainer.ready (node_modules\@nuxt\core\dist\core.js:51:7)
  at async Nuxt._init (node_modules\@nuxt\core\dist\core.js:478:5)


   ╭─────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                 │
   │   ✖ Nuxt Fatal Error                                                            │
   ╰─────────────────────────────────────────────────────────────────────────────────╯

error Command failed with exit code 1.
```

**Comment by PawFV** [comment]
My solution for now:

Downgrade to version 4.2.1.

`yarn add @nuxtjs/tailwindcss@4.2.1`

**Comment by yshrsmz** [comment]
relevant issue in nuxt/framework: https://github.com/nuxt/framework/issues/9063

**Comment by Sym313** [comment]
Same issue with:

@nuxtjs/tailwindcss: 5.3.5
nuxt: 2.15.8
platform: Mac (M1)

As pointed by a coworker, this line in @nuxt/postcss8/dist/index...:

`const {nuxt} = this;`

...crashes due to "this" being undefined: 

```
Nuxt Fatal Error
TypeError: Cannot destructure property 'nuxt' of 'this' as it is undefined.
```

The crash is not in Tailwind itself, but coming from a dependency. And not happening in previous verisons of Tailwind.

**Comment by chamyeongdo** [comment]
temporarily solved by using [`overrides`](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides) property.

npm version >= 8.3

```
// package.json
...
  "overrides": {
    "@nuxtjs/tailwindcss": {
      "@nuxt/kit": "3.0.0-rc.13"
    }
  },
...
```

```
> npm list @nuxt/kit
└─┬ @nuxtjs/tailwindcss@5.3.5
  └── @nuxt/kit@3.0.0-rc.13 overridden
```

**Comment by vahid-bagh3ri** [comment]
I have this Issue using v5.3.2 with nuxt@2.15.8 @danielroe

**Comment by misternian** [comment]
> 

good idea

**Comment by misternian** [comment]
> My solution for now:
> 
> Downgrade to version 4.2.1.
> 
> `yarn add @nuxtjs/tailwindcss@4.2.1`

good idea

**Comment by vahid-bagh3ri** [comment]
> > My solution for now:
> > Downgrade to version 4.2.1.
> > `yarn add @nuxtjs/tailwindcss@4.2.1`
> 
> good idea

By this action you will downgrade to tailwind v2, and it may cause some error, as it did in my project.

**Comment by lowbits** [comment]
For yarn users please use in your package.json
```
"resolutions": {
    "@nuxt/kit": "3.0.0-rc.13"
  }
```

**Comment by HuanDoan** [comment]
> My solution for now:
>
>Downgrade to version 4.2.1.
>
>```yarn add @nuxtjs/tailwindcss@4.2.1```

It works for me:

- OS: Mac 12.6
- Node version: v14.21.1
- Nuxt version: 2.15.8

**Comment by fahmiegerton** [comment]
Got same problem, i'm using npm, if i use yarn other errors thrown. Tried every suggestion in here but still same. Any other way?

**Comment by TuanHarry** [comment]
same issue

**Comment by Sym313** [comment]
> My solution for now:
> 
> Downgrade to version 4.2.1.
> 
> `yarn add @nuxtjs/tailwindcss@4.2.1`

This is the only workaround working for me too.

**Comment by yshrsmz** [comment]
Just for confirmation, this error still exists in v6.20.0 when used with Nuxt2

**Comment by tuannguyenminh2086** [comment]
> For yarn users please use in your package.json
> 
> ```
> "resolutions": {
>     "@nuxt/kit": "3.0.0-rc.13"
>   }
> ```

thanks. it's working

**Comment by StevenGrether** [comment]
> For yarn users please use in your package.json
> 
> ```
> "resolutions": {
>     "@nuxt/kit": "3.0.0-rc.13"
>   }
> ```
In case anyone needs the npm equivalent. It resolves the issue for now (nuxt 2.15.8, tailwind 6.2.0)
```
"overrides": {
    "@nuxt/kit": "3.0.0-rc.13"
}
```

**Comment by Aybee5** [comment]
Even after doing the following steps, I am still getting error
> rm -rf node_modules
> Deleting yarn.lock + .nuxt
> Adding resolutions for yarn
> Installing fresh packages

I got the following error from `Cannot read properties of undefined (reading 'length')` from composition/api

**Comment by mercs600** [comment]
`"overrides"` is easy to setup in when you have access to package.json, but what about libraries that use nuxt/tailwind module as dependency ? There is no way to setup `overrides`. 
Even if we force `"@nuxt/kit": "3.0.0-rc.13"` as dependency in the library. 
The problem is still there.

**Comment by gbyesiltas** [comment]
This is still an issue after @nuxt/kit 3.1.1 for me. Which, assuming it worked with 3.0.0-rc.13, isn't good news

**Comment by ineshbose** [comment]
Closing this issue as it is believed to be resolved/stale now - please feel free to comment if it is still an issue in the latest version of the module.
