### ISSUE TITLE
tailwinds 5.3.5 cannot working and encounter a error when I run the project. 

### ISSUE THREAD

**Issue by being8000** [nuxt-modules/tailwindcss#573]
### Version
@nuxtjs/tailwindcss: v5.3.5
nuxt: v3.0.0-rc.11
@nuxtjs/google-fonts: v3.0.0-1

### Steps to reproduce
1. before 5.3.5 version worked fine, but after recently removing node_modules and then reinstalling them, the project won't start.  And after I installed the latest version 6.1.2.  The project is running normally.  But nuxt-google-font cannot be used properly. 

### What is Expected?

nuxt-google-font should be worked. 

### What is actually happening?

nuxt-google-font is invalid

**Comment by being8000** [comment]
![image](https://user-images.githubusercontent.com/40756758/202615494-c04ddfa2-fac3-4c98-b107-ae6ae11a1807.png)

**Comment by sduduzog** [comment]
@saddam-azad  Installing the npm dependency `pathe` solves the issue above for me.

It is however worth addressing this dependency issue at some point
