### ISSUE TITLE
warning in terminal regarding utility classes not detected

### ISSUE THREAD

**Issue by wrench1815** [nuxt-modules/tailwindcss#574]
### Version
@nuxtjs/tailwindcss:  v6.1.3
nuxt:  v3.0.0

### Reproduction Link

https://stackblitz.com/edit/nuxt-tailcss-utility-warn

### Steps to reproduce

- Install `@nuxtjs/tailwindcss`
- run server

### What is Expected?

Clean terminal running Nuxt server

### What is actually happening?

There is a warning regarding missing utility classes.

```zsh
 WARN                                                                                                         13:12:45


 WARN  warn - No utility classes were detected in your source files. If this is unexpected, double-check the content option in your Tailwind CSS configuration.


 WARN  warn - https://tailwindcss.com/docs/content-configuration  
```

This happened on rc version of Nuxt 3 as well.

Although utility classes are working, So I do not know if it affects the classes generation or not, But I still considered opening an Issue just in case.

**Comment by ilkerdurmaz** [comment]
same here :(

**Comment by luabraggion** [comment]
this is happening because he is reading content in his tailwind.config files and did not find any classes. 
do the following go to your app.vue and put an h1 class="text-red-500" and restart the service here the problem was that.

**Comment by wilfredinni** [comment]
Same issue here. Wanted to use Nuxt in a new project at work, but having many troubles with tailwind and typescript

**Comment by PickleNik** [comment]
same here, didn't happen at first tho, but then started happening %)
tried editing tailwind.config as per [Tailwind Docs](https://tailwindcss.com/docs/guides/nuxtjs#3)
no luck so far
<img width="864" alt="Screenshot 2022-12-29 at 12 04 32 PM" src="https://user-images.githubusercontent.com/31113245/209985636-cbc44724-6273-4f71-b25a-38998bf71e74.png">

**Comment by PickleNik** [comment]
> this is happening because he is reading content in his tailwind.config files and did not find any classes. do the following go to your app.vue and put an h1 class="text-red-500" and restart the service here the problem was that.

This actually works, thanks, sorry for not reading first

**Comment by damisparks** [comment]
> this is happening because he is reading content in his tailwind.config files and did not find any classes.
> do the following go to your app.vue and put an h1 class="text-red-500" and restart the service here the problem was that.

@luabraggion Thank you for the solution. It solves the issue for me.

**Comment by wrench1815** [comment]
I see no point in keeping this issue open since the problem is not even a problem. It's just a mistake in understanding what the message is about. Since it tree-shakes the classes used and ofcourse if none is used, it gives a warning.

**Comment by PickleNik** [comment]
just a bad confusing warning imo
