### ISSUE TITLE
Slow build when using greedy globs in the content prop when building

### ISSUE THREAD

**Issue by Lilja** [nuxt-modules/tailwindcss#577]
### Version
@nuxtjs/tailwindcss: 6.1.3
nuxt: 3.0.0

### Reproduction Link
Tried to fork it, but ended up with errors when updating the dependencies to the latest. vue-router errors, so I abandoned that idea.

### Steps to reproduce
Add `./node_modules/<organization/package>/**/*.js` to the content section of your tailwind config

### What is Expected?
A reasonable time for search for js files and strings, <30 seconds.

### What is actually happening?
7 minutes of `nuxt build`
![image](https://user-images.githubusercontent.com/6134511/203071111-edf9e6fd-f9be-4e9a-a48f-14cb492fe3bd.png)

### Extras
Our organisation is putting our app's styling in other packages. We have set up
`./node_modules/@funnel-io/**/*.js` which works when building it with vite and other react apps. It seems like a problem for nuxt or this module.

**Comment by Atinux** [comment]
This is pretty tricky since we don't process anything for this particular Tailwind key 🤔
