### ISSUE TITLE
Suggestion for the Modules page design

### ISSUE THREAD

**Issue by Norbert-Brett** [nuxt-modules/tailwindcss#581]
### Contrast Issue

I was looking today at the Nuxt 3 modules section and I noticed that the colour contrast for the code snippets are really bad and unreadable, can't see the text nor the button.  If possible could you please check this issue and amend the colouring scheme for this area for a better UX. 

I attached a couple of screenshots to help you with this:

![Screenshot 2022-12-08 at 14 43 56](https://user-images.githubusercontent.com/60483492/206476036-82524185-3949-461f-9145-fe0c12296c39.png)

![Screenshot 2022-12-08 at 14 48 55](https://user-images.githubusercontent.com/60483492/206477236-d9c7286a-60f0-4d17-86bb-b2bebf86559d.png)

Wish you all the best!

PS:
Congrats with the Nuxt 3 stable release , amazing job.

**Comment by Atinux** [comment]
Fixed now, thank you!
