### ISSUE TITLE
Using the tailwind/ui plugin causes an undefined error

### ISSUE THREAD

**Issue by blowsie** [nuxt-modules/tailwindcss#585]
### Version
@nuxtjs/tailwindcss: ^6.2.0
nuxt: 3.0.0
@tailwindcss/typography: ^0.5.8
@tailwindcss/ui: ^0.7.2

### Reproduction Link

I haven't created one yet, but the example on the official docs is failing also

### Steps to reproduce
 - Fresh Nuxt 3.0 project
 - Add Tailwind
 - Add tailwind/ui

### What is Expected?
Successful build

### What is actually happening?
Looks like a CJS / ESM issue perhaps when the tailwindcss/typography plugin is trying to load the default theme

```bash
WARN  Failed to load Tailwind config at: ./tailwind.config.js Cannot read properties of undefined (reading '700')

  at D:/Projects/website/node_modules/.pnpm/@tailwindcss+typography@0.2.0/node_modules/@tailwindcss/typography/src/styles.js:14:38
```

![image](https://user-images.githubusercontent.com/308572/209690149-f6a45d60-f536-4b81-ab41-4a3cd3d4d3f0.png)

**Comment by blowsie** [comment]
Overriding the version of `@tailwindcss/typography` that `@tailwindcss/ui` uses internally fixes the issues, but I'm unsure of any other side effects.

```json
 "pnpm": {
    "overrides": {
      "@tailwindcss/typography": "^0.5.8"
    }
  }
  ```

**Comment by blowsie** [comment]
Has this been fixed or just closed without comment?

**Comment by ineshbose** [comment]
Hi, sorry I was doing an issue cleanup for the repository. Are you still experiencing this on the latest versions?

From my understanding, it seems to be a Tailwind configuration issue.

If using colors, use `tailwindcss/colors`: https://tailwindcss.com/docs/customizing-colors#using-the-default-colors
See related: #659
