### ISSUE TITLE
Add example for usage with Flowbite

### ISSUE THREAD

**Issue by zoltanszogyenyi** [nuxt-modules/tailwindcss#590]
### Is your feature request related to a problem? Please describe.

Hey peeps 👋

I'm one of the maintainers of the [Flowbite](https://github.com/themesberg/flowbite) library and we recently launched a Nuxt.js integration guide and decided to use this module. Here's the guide: https://flowbite.com/docs/getting-started/nuxt-js/.

I saw that on your website you have an example on how to use Daisy UI and Tailwind UI and considering that Flowbite is also a very popular component library (1.5m+ downloads on NPM) it could be great for the users on Nuxt Tailwind to also see a working example.

### Describe the solution you'd like

Create an example of page using Flowbite's blocks (https://flowbite.com/blocks/) and add it to the examples area on Nuxt Tailwind.

### Describe alternatives you've considered

We already built a starter project for this and have the main integration guide live on our documentation (https://flowbite.com/docs/getting-started/nuxt-js/).

### Additional context

Thanks for building this awesome module <3

**Comment by Atinux** [comment]
See https://github.com/nuxt-modules/tailwindcss/pull/605

**Comment by Atinux** [comment]
Flowbite looks promising, nice work ❤️‍🔥

**Comment by zoltanszogyenyi** [comment]
Hey @Atinux - thanks for the PR and the merge, we also referenced the module on our docs <3

**Comment by Atinux** [comment]
Some note on https://flowbite.com/docs/getting-started/nuxt-js/

Can you
- Rename `Nuxt.js` to Nuxt` ?
- Do you mind linking Nuxt to nuxt.com at least once at the beginning of the page so user can go to Nuxt docs?
- Could you update the logo to the latest version? https://nuxt.com/design-kit

**Comment by zoltanszogyenyi** [comment]
Hey @Atinux - sure, I'll do it today and have it deployed. I didn't notice the new logo, nice :)
