### ISSUE TITLE
CSS Intellisense not working

### ISSUE THREAD

**Issue by nazar1ua** [nuxt-modules/tailwindcss#593]
https://github.com/tailwindlabs/tailwindcss-intellisense/issues/663#issuecomment-1314825613
It is bug on module side

**Comment by nazar1ua** [comment]
I'm sorry, I looked into module code, and saw that it is problem on @tailwindlabs side with `resolveConfig.js` file

**Comment by nazar1ua** [comment]
But as a temporary workaround we can do this (at https://github.com/nuxt-modules/tailwindcss/blob/main/src/module.ts#L142-L148):
```ts
    const resolveConfig: any = await import('tailwindcss/resolveConfig.js').then(r => r.default || r)
    const resolvedConfig = resolveConfig(tailwindConfig)
    resolvedConfig.plugins = []
    addTemplate({
      filename: 'tailwind.config.cjs',
      getContents: () => `module.exports = ${JSON.stringify(resolvedConfig, null, 2)}`,
      write: true
    })
```

**Comment by nazar1ua** [comment]
Can I open pr @Atinux?

**Comment by Atinux** [comment]
Sure thing!

**Comment by leo91000** [comment]
For those who can't wait the fix, you can use `pnpm patch @nuxtjs/tailwindcss` and modify the `dist/module.mjs` with the @nazar1ua modification

**Comment by tkofh** [comment]
The current fix solves the base resolved configuration, but it does not handle plugins from Tailwind Presets. 

Reproduction: https://stackblitz.com/edit/nuxt-starter-afebar

I believe we could expand upon the fix like this:
```typescript
const resolveConfig: any = await import("tailwindcss/resolveConfig.js").then((r) => r.default || r)
const resolvedConfig = resolveConfig(tailwindConfig)
resolvedConfig.plugins = []
for (const preset of resolvedConfig.presets) {
  if(preset.plugins != null) {
    preset.plugins = []
  }
}
addTemplate({
  filename: "tailwind.config.cjs",
  getContents: () => `module.exports = ${JSON.stringify(resolvedConfig, null, 2)}`,
  write: true,
})
```

Can I open a PR to add this?

**Comment by nazar1ua** [comment]
Yes

**Comment by ERPedersen** [comment]
This problem also occurs for me when using `purge.options.safelist` or just `safelist` in the root of the tailwind config. If i remove any of these properties, the intellisense starts working again.

# Example 1

**tailwind.config.js:**

```javascript
export default {
  purge: {
    options: {
      safelist: [
        { pattern: /(bg|text)-./ },
      ],
    },
  },
}
```

**Becomes:**

```cjs
module.exports = {
  'purge': {
    'options': {
      'safelist': [
        {
          'pattern': {},
        },
      ],
    },
  },
  'safelist': [
    {
      'pattern': {},
    },
  ],
};
```

# Example 2 (Tailwind ^3)

```javascript

export default {
  safelist: [
    { pattern: /(bg|text)-./ },
  ],
}

```

**Becomes:**

```cjs
module.exports = {
  "safelist": [
    {
      "pattern": {}
    }
  ],
}
```

**Comment by ineshbose** [comment]
Is this still being experienced? This has not been an issue for me recently - I'm not sure what fixed it, maybe the extension was updated in the background, but all intellisense is working flawlessly now.
