### ISSUE TITLE
PurgeCSS is ignoring components registered globally

### ISSUE THREAD

**Issue by yabuking84** [nuxt-modules/tailwindcss#597]
Tailwind classes doesn't work on components that were registered from a plugin globally. but in your local component if you add a tailwind class it will work. I think PurgeCSS is ignoring components registered globally.

### Version
@nuxtjs/tailwindcss: ^6.2.0
nuxt: ^3.0.0

### Reproduction Link

https://github.com/megapossy/tawingski.git 
branch: tailwind-issue-plugin-components

### Steps to reproduce
install nuxt and create a plugin that register components globally.
From the repo link, install and run dev then go to /login in browser.

### What is Expected?
The Remember Me text should have the text-blue-900. If you inspect there are no css styles to it.

### What is actually happening?
 I think PurgeCSS is ignoring components registered globally.

**Comment by yabuking84** [comment]
Just solved this, on tailwind.config.ts just add 
`export default <Partial<Config>>{
  theme: {
    extend: {},
  },
  content: [
  '${srcDir}/plugins/**/*.vue'
 ],
};`

**Comment by bbhxwl** [comment]
> Just solved this, on tailwind.config.ts just add `export default <Partial<Config>>{ theme: { extend: {}, }, content: [ '${srcDir}/plugins/**/*.vue' ], };`

srcDir   How to define this variable?
