### ISSUE TITLE
Nuxt 6.2.0 brake Nuxt

### ISSUE THREAD

**Issue by iTechSebastianoLaini** [nuxt-modules/tailwindcss#598]
### Version
@nuxtjs/tailwindcss: 6.2.0
nuxt: 2.15.8

### Steps to reproduce
Update Tailwind from 6.1.3 to 6.2.0 would throw an error in the Nuxt dev server

### What is actually happening?
Nuxt dev server can't start
![image](https://user-images.githubusercontent.com/61748264/213987990-fc320dd2-a7e8-48ad-8ab7-761b7c110ea8.png)

**Comment by adippel** [comment]
I have the same setup wit the same error.

**Comment by iTechSebastianoLaini** [comment]
for us that we are using yarn seems to work the proposed solution:

```
"resolutions": {
    "@nuxt/kit": "3.0.0-rc.13"
}
```
