### ISSUE TITLE
Typescript error in nuxt.config with defineNuxtConfig

### ISSUE THREAD

**Issue by Archetipo95** [nuxt-modules/tailwindcss#601]
Object literal may only specify known properties, and 'tailwindcss' does not exist in type 'NuxtConfig'

### Version
@nuxtjs/tailwindcss: latest
nuxt: latest

![Screenshot 2023-01-26 at 11 45 18](https://user-images.githubusercontent.com/11798239/214817127-e2444cd0-daf2-43a4-9ae6-e558385ab442.png)
![Screenshot 2023-01-26 at 11 45 29](https://user-images.githubusercontent.com/11798239/214817131-1e6d45a5-06cb-4357-b87c-d548a6586ec9.png)

**Comment by ineshbose** [comment]
Is `@nuxtjs/tailwindcss` added to your modules? A reproduction would help.

**Comment by Archetipo95** [comment]
@ineshbose yes I confirm, `@nuxtjs/tailwindcss` is in modules and I used `npx nuxi prepare`

**Comment by Archetipo95** [comment]
Found the problem... sorry for wasting your time, my Nuxt version was 3.1.0 and not 3.1.1
