### ISSUE TITLE
Issue with `extends` + `@nuxtjs/tailwind` not taking `srcDir` into account

### ISSUE THREAD

**Issue by mukundshah** [nuxt-modules/tailwindcss#602]
### Version
------------------------------
- Operating System: `Linux`
- Node Version:     `v16.18.1`
- Nuxt Version:     `3.1.1`
- Nitro Version:    `2.1.0`
- Package Manager:  `pnpm@7.26.0`
- Builder:          `vite`
- User Config:      `extends`, `app`, `modules`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.3.0`
- Build Modules:    `-`
------------------------------

### Reproduction Link
N/A

### Steps to reproduce
- Setup a nuxt project with `@nuxtjs/tailwindcss` and  `nuxt-seo-kit`
- Add `nuxt-seo-kit` to `extends` list in `nuxt.config.ts`
- Set `srcDir` to `src`
- Move `app.vue` into `src` dir
- Replace `<NuxtWelcome />` with
```html
    <div class="w-10 h-10 bg-red-500"></div>
```

### What is Expected?
All the tailwindcss classes should be resolved properly.

### What is actually happening?
So, I was trying to use nuxt-seo-kit which is a Nuxt Layer. Therefore, I added nuxt-seo-kit to the extends list in the nuxt.config.ts
But then I started to have issue with almost half of tailwindcss classes not being resolved.

After 2 days of trying everything, I redid everything from scratch. 
I created a new nuxt project with nuxt 3.1.1 and @nuxt/tailwindcss 6.3.0 .
I added the nuxt-seo-kit to  the nuxt.config.ts in the extends list.
Everything was fine.
So as usual, I put everything to `src/` dir and in the config I added srcDir: "src". Now the problem reappeared. Only half of the CSS classes were being resolved.

I'm not sure where this is coming from, as nothing is being logged in the console or terminal. 

In the given context, only `w-10 h-10` is resolved. However, tailwind playground is working as usual.

This is the structure of a working project:
```txt
├── app.vue
├── layouts
│  └── default.vue
├── node_modules
├── nuxt.config.ts
├── package.json
├── pages
│  └── index.vue
├── pnpm-lock.yaml
├── README.md
├── tailwind.config.ts
└── tsconfig.json
```

**Comment by Atinux** [comment]
It would help if you can provide a reproduction with Stackblitz or a GH repo @mukundshah

**Comment by optimistic-raisin** [comment]
https://stackblitz.com/edit/nuxt-starter-ehxzhu?file=using-srcDir/nuxt.config.ts @Atinux

**Comment by mukundshah** [comment]
https://stackblitz.com/edit/nuxt-starter-ehxzhu?file=using-srcDir/nuxt.config.ts @Atinux

This time, none of the classes are being resolved.

**Comment by damienroche** [comment]
I have the same issue.
I would like to set a custom `tailwind.config` file for a folder that extends my `base` `nuxt.config.ts` file

<img width="990" alt="Capture d’écran 2023-02-01 à 10 14 55" src="https://user-images.githubusercontent.com/1529058/216001737-55c88efe-46fe-443d-a28b-17c8a876c3c3.png">

<img width="984" alt="Capture d’écran 2023-02-01 à 10 15 01" src="https://user-images.githubusercontent.com/1529058/216001768-8cab2dc0-8837-46cc-9fdb-ee0dad58df36.png">

<img width="932" alt="Capture d’écran 2023-02-01 à 10 15 14" src="https://user-images.githubusercontent.com/1529058/216001787-37ff5801-7723-4fee-9137-aea38068e581.png">

When i run `pnpm nuxt dev .starter` and go to the Tailwind Viewer url, primary color is extracted from my base `tailwind.config` file, also I think JIT mode doesn't look for files in `.starter` but in `base` directory

<img width="1051" alt="Capture d’écran 2023-02-01 à 10 16 26" src="https://user-images.githubusercontent.com/1529058/216001809-0d5e4399-5b38-42bf-aac1-c12b0c93682b.png">

**Comment by damienroche** [comment]
After updating base `nuxt.config.ts` file with the following options, it seems to work as expected : 
```javascript
export default defineNuxtConfig({
  modules: [
    '@nuxt/content',
    '@nuxtjs/tailwindcss'
  ],
  //...
  tailwindcss: {
    configPath: '~/tailwind.config'
  }
})
```

**Comment by Atinux** [comment]
The working demo from @damienroche 

https://codesandbox.io/p/sandbox/quiet-fog-6zvdr2?file=%2Fyarn.lock&selection=%5B%7B%22endColumn%22%3A14%2C%22endLineNumber%22%3A807%2C%22startColumn%22%3A2%2C%22startLineNumber%22%3A807%7D%5D
