### ISSUE TITLE
How to output .css files?

### ISSUE THREAD

**Issue by ekrausso** [nuxt-modules/tailwindcss#606]
How to avoid styles being injected inline in the `<head>` ?  I tried `extractCss: true`  but nothing changes.  Can this be done in Nuxt 2 ?

**Comment by ineshbose** [comment]
This is the default behaviour in Nuxt 3. In Nuxt 2, you have https://nuxtjs.org/docs/configuration-glossary/configuration-build/#extractcss - if this isn't working, please feel free to share a reproduction and we'll clear it up. 🙂
