### ISSUE TITLE
No utility classes detected in source files (content option)

### ISSUE THREAD

**Issue by ThimoDEV** [nuxt-modules/tailwindcss#607]
### Version
@nuxtjs/tailwindcss:  v6.3.0 and above
nuxt:  v3.1.2

### Reproduction Link
[](https://github.com/ThimoDEV/nuxt3-tailwind-warning-content)

### Steps to reproduce
- yarn install
- yarn dev

### What is Expected?
Tailwind should recognize the content form its config, 

yet it throws warnings in both @nuxt/tailwindcss as in the configuration which is provided by tailwind itself. To see the the warning with the other tailwind config, you can switch branch in the repo.

### What is actually happening?
![image](https://user-images.githubusercontent.com/68739517/217676486-d640bd7b-8342-49cc-ab5b-9c4b61425555.png)

**Comment by ineshbose** [comment]
Couldn't find a provided reproduction!

But this issue is when there are no CSS classes in your Nuxt app *yet*.

**Comment by ThimoDEV** [comment]
> Couldn't find a provided reproduction!
> 
> But this happens when there are no CSS classes in your Nuxt app _yet_.

Isn't that a bit weird to tell the user? I would expect that if I install a package but I didn't use it yet that it shouldn't give warnings of any form, in this case I wouldn't expect such warnings unless my config is wrong or I started using tailwind classes.

**Comment by ineshbose** [comment]
The warning is from Tailwind and the module is forwarding it - I believe it's their decision to have that.
