### ISSUE TITLE
nuxt 2.16 has postcss8 by default

### ISSUE THREAD

**Issue by simllll** [nuxt-modules/tailwindcss#609]
### Version
@nuxtjs/tailwindcss: 6.3.1
nuxt: 2.16.0

### Steps to reproduce
install nuxt 2.16 and add nuxtjs/tailwind, you get an error like:
 FATAL  Cannot destructure property 'nuxt' of 'this' as it is undefined.                                                                                                                                              13:32:58
 which his actually covered here already: https://github.com/nuxt-modules/tailwindcss/issues/572
but actually this is caused by installing postcss8, which is not needed anymore on nuxt 2.16 as it is now the default see https://github.com/nuxt/nuxt/releases/tag/v2.16.0

### What is Expected?
do not install postcss8 for nuxt 2.16.. i tested it locally by just commeting out:
```js
if (isNuxt2()) {
      // await installModule("@nuxt/postcss8");
    }
```
in dist/module.mjs
and eveything seems working perfectly fine :-)

### What is actually happening?
it install postcss8 and breaks.

**Comment by nathakits** [comment]
I'm also having this issue after upgrading Nuxt to 2.16.0
