### ISSUE TITLE
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/css"

### ISSUE THREAD

**Issue by nachoadjust** [nuxt-modules/tailwindcss#613]
### Version
```js
"@nuxtjs/tailwindcss": "^6.4.0",
"nuxt": "^3.1.2"
```

### Reproduction Link
https://www.loom.com/share/f33768c4ef004531967e4d69780313cf

### Steps to reproduce
1. Install the latest nuxt.
2. Install @nuxtjs/tailwindcss with the minimal setup.
3. Add some basic tailwind helper classes to some element.
4. Start localhost.

### What is Expected?
- Styles should render on screen.

### What is actually happening?
- Styles don't get rendered.
- I am getting this error when loading the page:
`Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/css". Strict MIME type checking is enforced for module scripts per HTML spec.`

Error disappears if I hard-reload and re appears next time I load the page again.

#### References
- https://github.com/nuxt-modules/tailwindcss/issues/387
None of the solutions mentioned here have worked for me.

**Comment by bbroekhuizen** [comment]
@nachoadjust I have the same issue, but it seems to work in FireFox and Safari. But not in Chrome. Can you try it in FireFox and Safari?

**Comment by nachoadjust** [comment]
@bbroekhuizen you are correct.

✅ If browser is Safari, FFox or Chrome Incognito it works well.

❌ If browser is Chrome + NOT incognito it fails.

_Sidenotes:_ 
For chrome: 
I disabled all chrome plugins I have installed  as you mentioned (adblocker, Analytics, etc) in a wild hope that they might be influencing somehow, but it didn't had any effect.

**Video:**
https://www.loom.com/share/e232033f2ca342c88703e02a0bb19088

**Comment by ineshbose** [comment]
Minor thing I noticed in the first video - the CSS path should be in `nuxt.options.tailwindcss.cssPath`. Is this still an issue by the way? If so, please feel free to comment and I'll reopen it (doing an issue cleanup right now).

**Comment by bbroekhuizen** [comment]
@ineshbose Sorry for the long delay. But the issue still persists for me. I've added `tailwindcss: {
    cssPath: '~/assets/css/tailwind.css',
  }` to the `nuxt.config.ts` file but i don't get the expected result.

**Comment by ineshbose** [comment]
@bbroekhuizen thanks for reporting. Do you think you could provide a reproduction over Stackblitz please? You can use this as a starter- https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz?file=README.md

**Comment by bbroekhuizen** [comment]
@bbroekhuizen Thanks, wil do.

**Comment by bbroekhuizen** [comment]
@ineshbose Sadly can't reproduce it on StackBlitz. https://stackblitz.com/edit/github-eqxyuq?file=package.json,nuxt.config.ts,assets%2Fcss%2Ftailwind.css

**Comment by ineshbose** [comment]
@bbroekhuizen hmm.. it'll be difficult to triage this.. could be something related to your system? Minor thing I noticed in your Nuxt configuration is you have added `'~/assets/css/tailwind.css'` to `nuxt.options.css` - I'd recommend you remove that because the module adds it for you.

**Comment by bbroekhuizen** [comment]
@ineshbose It seems to work with a hard refresh `Cmd + Shift + R` it works again, and you need to do this when you start the server. I think this is not related to this module, but more something to do with Vue 3 / Nuxt 3 / Vite caching strategy in combination with Chrome.

**Comment by mirikqq** [comment]
> @ineshbose It seems to work with a hard refresh `Cmd + Shift + R` it works again, and you need to do this when you start the server. I think this is not related to this module, but more something to do with Vue 3 / Nuxt 3 / Vite caching strategy in combination with Chrome. For now, you can keep this issue "Closed". Thanks for your time.

Have you solved this error? Encountered the same thing without using tw at all
