### ISSUE TITLE
Development Class Changes Not Properly Applied After Page Reload In Nuxt >=3.1.1

### ISSUE THREAD

**Issue by JacobLindelof** [nuxt-modules/tailwindcss#620]
### Version
@nuxtjs/tailwindcss: 6.4.1
nuxt: >=3.1.1

### Reproduction Link

https://github.com/JacobLindelof/nuxt-tailwind-testing

### Steps to reproduce
1. Install dependencies.
2. Run dev server.
3. Change BG color class in app.vue.
4. Refresh page.

### What is Expected?
Changed be color correctly appears one page is refreshed.

### What is actually happening?
Previous state before changes are sent to the client instead.

This issue does not re-produce on CodeSandbox, but I have duplicated it with the given repo on my desktop and laptop. Both running windows. Maybe the issue is somehow windows related? Downgrading Nuxt from 3.1.1 to 3.1.0 does fix the issue so not sure if the issue is something in Nuxt or the Tailwind module. 

![Code_Hqjf5SaQbr](https://user-images.githubusercontent.com/13141332/219956097-0bbc8711-28e1-4f78-b90e-57d50048dbc9.gif)

**Comment by Skyward176** [comment]
Im getting something similar where I set a flex layout, it works. I refresh, and it breaks.

**Comment by JacobLindelof** [comment]
> 

Your issue is basically the same as mine. I've noticed all of the same behavior as you. For what its worth downgrading to Nuxt 3.1 does fix the issue completely, and you're not missing out on too much. 

I haven't fully tested it, but I think the same behavior happens if you install Tailwind without using the module as well which might indicate that it's actually an issue in the main Nuxt package instead of the module.

**Comment by Skyward176** [comment]
I've also noticed the issue with straight tailwindcss, installed manually. However, downgrading to Nuxt 3.1.0 has made no difference for me.

**Comment by fouteox** [comment]
Hi, I have exactly the same problem here.

**Comment by ineshbose** [comment]
Hi, does this issue persist with the latest versions? It seems to be very specific to some systems/browsers, so I'd ask you to restart the server and check for any cache. HMR improvements are also being investigated (#682).

**Comment by JacobLindelof** [comment]
> Hi, does this issue persist with the latest versions? It seems to be very specific to some systems/browsers, so I'd ask you to restart the server and check for any cache. HMR improvements are also being investigated (#682).

I don't believe it is an issue anymore in later versions. At least not with my development environment.
