### ISSUE TITLE
tailwindcss are called so many times

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt-modules/tailwindcss#621]
### Version
@nuxtjs/tailwindcss: 6.4.1
nuxt: 3.2.2

### Steps to reproduce

will do it soon

### What is actually happening?

![image](https://user-images.githubusercontent.com/45267552/220339340-ddc48fed-50f0-404e-aff0-21d3f76cdac8.png)

**Comment by Barbapapazes** [comment]
It's not happening in 6.3.0

**Comment by Barbapapazes** [comment]
Infinity of tailwind file is added.

**Comment by Barbapapazes** [comment]
could be related to vite https://github.com/vitejs/vite/blob/main/packages/vite/src/client/client.ts#L190

**Comment by Atinux** [comment]
Happy to get some help on this 🙏

**Comment by Barbapapazes** [comment]
Yes, i'm trying to understand when this happens but I still don't understand why

**Comment by Atinux** [comment]
Maybe with the vite plugin we added?

**Comment by Barbapapazes** [comment]
It seems that it happens because my computer is too slow to respond to another call is made by vite.

![image](https://user-images.githubusercontent.com/45267552/221606395-8cbb94ae-6770-4b60-bade-d8896047f57d.png)

**Comment by Hiratake** [comment]
Hi, I had the same problem.
I don't know what caused the problem, but after deleting ".nuxt", "node_modules", and "package-lock.json", and re-installing the dependencies with "npm install", it works correctly.

**Comment by Barbapapazes** [comment]
Not able to reproduce since weeks so close the issue.
