### ISSUE TITLE
static site with `npm run generate` doesn't include styles unlike `npm run dev`   

### ISSUE THREAD

**Issue by vinosamari** [nuxt-modules/tailwindcss#623]
### Version
@nuxtjs/tailwindcss: v4.2.1
nuxt: v2.15.8

### Reproduction Link
[Github Repo](https://github.com/vinosamari/sportswire)
[Vercel live deployment](https://sportswire.vercel.app)
[Render live deployment](https://sportswire.onrender.com)

### Steps to reproduce
1. Clone the repo & install dependencies
2. Run `npm run build` -> `npm run generate` -> `npm run start`

### What is Expected?
The website is expected to build with all the styles as it does in `npm run dev` (screenshot below).

![localhost_3000_ (1)](https://user-images.githubusercontent.com/60850993/222386819-1350e853-047f-43a6-b3aa-07f5b24844be.png)

### What is actually happening?
Generating the static website totally ignores styling that isn't vanilla css (only header and subheader font families from styles.css are present. Screenshot below)

![localhost_3000_ (2)](https://user-images.githubusercontent.com/60850993/222388177-f4f71042-e2ed-42cc-8f24-5ef0313cb505.png)

**Comment by sebrax** [comment]
I was having the same issue while using version 4.2.1 and solved by upgrading to 6.4.0.

**Comment by vinosamari** [comment]
@sebrax Did same and it works like a charm. Thank you! Does this mean TW is slowly dropping support of Nuxt 2.x?

**Comment by ineshbose** [comment]
Version 6 supports both Nuxt 3 and Nuxt 2 - I believe in the next major version, Nuxt 2 support may be dropped (EOL).
