### ISSUE TITLE
Generate unresolved version of tailwind.config.cjs

### ISSUE THREAD

**Issue by asen23** [nuxt-modules/tailwindcss#626]
### Is your feature request related to a problem? Please describe.

Tailwind intellisense developer has stated that the extension aren't supposed to use resolved version of tailwind config [here](https://github.com/tailwindlabs/tailwindcss-intellisense/issues/663#issuecomment-1316788128). Although it kinda works now, the resolved version has caused problem if the config contained some plugin like described here #584 and #565.

### Describe the solution you'd like

Generate unresolved tailwind config alongside the resolved one. Preferably, the unresolved one use the name "tailwind.config.cjs" and the resolved use other name, so it doesn't conflict with the extension config auto discovery.

### Describe alternatives you've considered

In the [tailwind extension issue](https://github.com/tailwindlabs/tailwindcss-intellisense/issues/663#issuecomment-1316788128), the developer suggested ignoring .nuxt folder and create tailwind.config.cjs manually. Although it works, I kinda prefer to put all of my config in the nuxt.config.ts.

**Comment by ineshbose** [comment]
Wouldn't the unresolved version just be your [default](https://github.com/tailwindlabs/tailwindcss/blob/eadd6e5de93e3011cd786c3aba1991364d7c80ea/stubs/config.simple.js)/provided config (that can be defined in `tailwind.config.js` in rootDir)?

The next step that happens in resolution is passing the provided config (also merged with configs in layers) with the above default config and layer paths to merge into one object using [defu](https://github.com/unjs/defu).

Then that is passed to TailwindCSS [`resolveConfig`](https://github.com/tailwindlabs/tailwindcss/blob/eadd6e5de93e3011cd786c3aba1991364d7c80ea/src/public/resolve-config.js).

**Comment by asen23** [comment]
> Wouldn't the unresolved version just be your [default](https://github.com/tailwindlabs/tailwindcss/blob/eadd6e5de93e3011cd786c3aba1991364d7c80ea/stubs/config.simple.js)/provided config (that can be defined in `tailwind.config.js` in rootDir)?

Yes, that is correct, but I think not everyone has tailwind.config.js and instead use nuxt.config.ts to configure tailwind. I already described the alternatives to just make tailwind.config.js instead of putting the config in nuxt.config.ts. So I think it is nice to have the unresolved version created from the nuxt.config.ts

**Comment by ineshbose** [comment]
Do you think v6.6.6 that includes #655 would help?

**Comment by asen23** [comment]
I think it contribute to a solution but it's not there yet i think? My current workaround is to create inline module to write to content of unresolved file to tailwind.config.js and ignoring the cjs version in tailwind extension. But the null plugin problem still persist, i haven't found any clue how to fix that. About your comment in #584 , what exactly esm does/change to enable generating the unresolved one?

**Comment by ineshbose** [comment]
The reason why a resolved one was generated was that Tailwind required configuration only in CommonJS, but v3.3 onwards configuration in ESM has been supported, so resolving it into `tailwind.config.cjs` is not required (#660) and IntelliSense should directly pick up your configuration whether it is in ESM or TypeScript. However, as you mentioned, some use `nuxt.config.ts` to configure Tailwind, and in that case, #655 places the hook to be before resolution, so you could add your own module to add a template for that like so:

```ts
export default defineNuxtConfig({
  modules: [
    '@nuxtjs/tailwindcss',
    (options, nuxt) => { nuxt.hook('tailwindcss:config', (config) => addTemplate({ filename: 'tailwind.config.js', content: () => `module.exports = ${JSON.stringify(config)}` }))} // something like this
  ],
  tailwindcss: {} // whatever you put in
})
```

While we're manoeuvring to provide a solution to this, I don't believe that this feature will fully be included in the module (unless there's demand), so I'm asking you to add a custom module.

**Comment by asen23** [comment]
Ah i see, if #660 does create tailwind config as if the user created tailwind.config.ts manually, then it think it solves the problem then. I ask for the unresolved version cause the resolved version cause issue with tailwind extension and if the module provide proper config for tailwind extension to use then i don't really need to mess with custom module.

**Comment by asen23** [comment]
Hello, i tried the new version and i think tailwind extension still wont work out of the box. I still need to create tailwind.config.* or the extension wont give me intellisense. I think you still need to give the extension some kind of config from the defineNuxtModule. Is it possible to somehow export the option from defineNuxtModule? I think it will solve the issue.

**Comment by ineshbose** [comment]
You can read this: https://github.com/nuxt-modules/tailwindcss/issues/565#issuecomment-1542891104

What you'd like is:

```ts
import { defineNuxtModule, addTemplate } from '@nuxt/kit'

export default defineNuxtModule({
  setup (options, nuxt) {
    // - nuxt.hook('tailwindcss:resolvedConfig', (config) => {
    nuxt.hook('tailwindcss:config', (config) => { // as you are looking for unresolved version
      addTemplate({
        filename: 'tailwind.config.cjs', // gets prepended by .nuxt/
        getContents: () => `module.exports = ${JSON.stringify(config)}`,
        write: true
      })
    })
  }
})
```

**Comment by asen23** [comment]
> You can read this: [#565 (comment)](https://github.com/nuxt-modules/tailwindcss/issues/565#issuecomment-1542891104)
> 
> What you'd like is:
> 
> ```ts
> import { defineNuxtModule, addTemplate } from '@nuxt/kit'
> 
> export default defineNuxtModule({
>   setup (options, nuxt) {
>     // - nuxt.hook('tailwindcss:resolvedConfig', (config) => {
>     nuxt.hook('tailwindcss:config', (config) => { // as you are looking for unresolved version
>       addTemplate({
>         filename: 'tailwind.config.cjs', // gets prepended by .nuxt/
>         getContents: () => `module.exports = ${JSON.stringify(config)}`,
>         write: true
>       })
>     })
>   }
> })
> ```

Isn't this just the old behaviour? The main problem i have with that is it doesn't support plugin. If i want to use plugin and have intellisense i need to create tailwind.config.* or it wont give me autocomplete. If you think it is impossible to do, atleast put a note in the docs. If it possible, then will it be implemented?

**Comment by ineshbose** [comment]
It isn't possible - I'll update the docs - you'll need to create `tailwind.config`.
