### ISSUE TITLE
Tailwind JIT doesn't pick up classes when extending off a project where `srcDir` is set

### ISSUE THREAD

**Issue by warflash** [nuxt-modules/tailwindcss#628]
### Version
@nuxtjs/tailwindcss: 6.4.0
nuxt: v3.2.3

### Reproduction Link
Can't make stackblitz reproduce because vite throws access issue errors when 2 nuxt projects are present for me atm

### Steps to reproduce
Set the `srcDir` to something like `src` in the nuxt config of the project you want to use as a base. When extending that base project Nuxt picks up components just fine so the `srcDir` generally is respected but Tailwind jit doesnt pick up the classes used there.

### What is Expected?
The jit compiler should be able to pick up classes regardless of `srcDir` in the base project.

### What is actually happening?
Classes are missing from the compiler output. Removing the `srcDir` prop from the nuxt config and placing the component folder in the root of the projected works around the issue.

**Comment by RomainMazB** [comment]
Hi @warflash , did you read that part of the documentation?
https://tailwindcss.nuxtjs.org/getting-started/options#configpath
specifically the note:
> If you customize the [srcDir](https://nuxt.com/docs/api/configuration/nuxt-config#srcdir) property in your `nuxt.config` file, you'll have to update the `configPath` value to `'~~/tailwind.config'` (`~~` is the alias for [rootDir](https://nuxt.com/docs/api/configuration/nuxt-config#rootdir)) for the tailwind.config file to be recognized properly. Read more in the [Issue #114](https://github.com/nuxt-community/tailwindcss-module/issues/114#issuecomment-698885369).
