### ISSUE TITLE
extraModules is not iterable error

### ISSUE THREAD

**Issue by TechAkayy** [nuxt-modules/tailwindcss#630]
@nuxtjs/tailwindcss: 6.5.0
nuxt: 3.2.3

I'm very randomly getting the below error and it's a little hard to replicate. I will keep trying to provide a reproduction. But it happens usually after tailwind.config.js (configPath) / tailwind.css (cssPath) are updated and when I see the "Please restart the Nuxt server to apply changes" warning message. 

![image](https://user-images.githubusercontent.com/73772701/224870996-3f1f6315-8b24-483d-a3b8-0b9b53add767.png)

### What is actually happening?

![image](https://user-images.githubusercontent.com/73772701/224870251-98d0bf61-89b5-459c-9a42-f282a2a29234.png)

Thanks for looking into this.

**Comment by ineshbose** [comment]
What's the file preview in the screenshot? Is it `@nuxtjs/tailwindcss/dist/module.mjs`?

Does this continue with the latest versions of Nuxt and this module?

**Comment by ineshbose** [comment]
Fix coming in #672

**Comment by TechAkayy** [comment]
Thanks bunch 🙏🏾
