### ISSUE TITLE
Get Tailwind Css file from node_modules

### ISSUE THREAD

**Issue by agracia-foticos** [nuxt-modules/tailwindcss#632]
I have our "custom" tailwind css in node_modules.

It's a tailwind css custom with storybook.

Hoy we can import it to our project and use it like main tailwind css?

this is our node_modules folder
![image](https://user-images.githubusercontent.com/77386602/225305542-42444199-f4fb-4500-a138-9cbf94622159.png)

we import the css like a module 
in genesis-design-system we have:

nuxt.js file

```ts
import { defineNuxtModule } from '@nuxt/kit'
import { fileURLToPath } from 'node:url'

export default defineNuxtModule({
  meta: {
      name: '@foticos/genesis-design-system',
      compatibility: {
          nuxt: '^3.0.0'
      }
  },
  hooks: {
    'components:dirs'(dirs) {
      // Add ./components dir to the list
      dirs.push({
        path: fileURLToPath(new URL('./src/components', import.meta.url)),
        prefix: ''
      })
    }
  },
  setup (options, nuxt) {
    nuxt.options.css.push(fileURLToPath(new URL('./dist/genesis.css', import.meta.url)))
  }
})
```

Thanks in advance

**Comment by Atinux** [comment]
Why not using the `cssPath` option of the tailwind module?

**Comment by agracia-foticos** [comment]
We have all the tailwind information in StoryBook.

The StoryBook exports the tailwindCss through a module:

`import { defineNuxtModule } from '@nuxt/kit'
import { fileURLToPath } from 'node:url'

export default defineNuxtModule({
  meta: {
      name: '@foticos/genesis-design-system',
      compatibility: {
          nuxt: '^3.0.0'
      }
  },
  hooks: {
    'components:dirs'(dirs) {
      // Add ./components dir to the list
      dirs.push({
        path: fileURLToPath(new URL('./src/components', import.meta.url)),
        prefix: ''
      })
    }
  },
  setup (options, nuxt) {
    nuxt.options.css.push(fileURLToPath(new URL('./dist/genesis.css', import.meta.url)))
  }
})`

In the project, we put cssPath to false, because the tailwindcss is duplicated.

But in genesis.css isnt apply postcss for purge all unused css.

**Comment by ineshbose** [comment]
Sorry - I'd love to help you with this, but maybe it's a bit difficult to understand what's going on here. Were you able to find an answer by now? If not, it would be really appreciated if you could provide a reproduction that can illustrate this scenario better.

**Comment by ineshbose** [comment]
Seems that this issue turned into #639
