### ISSUE TITLE
HMR tailwind config updates

### ISSUE THREAD

**Issue by TechAkayy** [nuxt-modules/tailwindcss#633]
This is related to https://github.com/nuxt-modules/tailwindcss/issues/622, and thanks for letting us restart in v3.3.1.

It seems like the requirement to restart on tailwind config is the current norm.

I'm curious to know if by any chance our module can support HMR for tailwind config updates, and avoid restart. Is it technical possible? If not, would love to learn the reason behind it. Thanks in advance.

**Comment by Atinux** [comment]
Maybe in Tailwind V4 but as far as I know I don't think this is currently possible in the current state.

**Comment by TechAkayy** [comment]
Thanks for your note. Will stay tuned for tw v4. Cheers!
