### ISSUE TITLE
Export tailwind css like a module

### ISSUE THREAD

**Issue by agracia-foticos** [nuxt-modules/tailwindcss#639]
I have one Storybook with tailwind css.

We want export the components of storybook/tailwind and the css of storybook/tailwind

![image](https://user-images.githubusercontent.com/77386602/226357446-cf5a6359-1d51-47fb-9114-698bada80517.png)

Out entry point of tailwindcss is ./src/styles/main.css

In our nuxt.js (module) we have this:

```ts
import { defineNuxtModule } from '@nuxt/kit'
import { fileURLToPath } from 'node:url'

export default defineNuxtModule({
  meta: {
      name: 'storybook',
      compatibility: {
          nuxt: '^3.0.0'
      }
  },
  hooks: {
    'components:dirs'(dirs) {
      // Add ./components dir to the list
      dirs.push({
        path: fileURLToPath(new URL('./src/components', import.meta.url)),
        prefix: ''
      })
    }
  },
  setup (options, nuxt) {
    nuxt.options.tailwindcss.cssPath.push(fileURLToPath(new URL('./src/styles/main.css', import.meta.url)))
  }
})
```

But this throws an error...

¿How we can export main.css like the path of tailwind css in a module?

Thanks in advance

**Comment by Atinux** [comment]
> But this throws an error...

And what is it?

**Comment by agracia-foticos** [comment]
> ```ts
> nuxt.options.tailwindcss.cssPath.push(fileURLToPath(new URL('./src/styles/main.css', import.meta.url)))
> ```

![image](https://user-images.githubusercontent.com/77386602/226543279-2d6a3401-b166-4ef6-bd00-0475e9aa042b.png)

But i dont have anything in debug Visual Studio console

![image](https://user-images.githubusercontent.com/77386602/226543370-a80dc013-1f49-4ee6-9d6d-b74fd7168a41.png)

![image](https://user-images.githubusercontent.com/77386602/226543402-853df39d-e96a-435e-a563-79ebf52bbfb7.png)

**Comment by Atinux** [comment]
Could you please share a reproduction so we can help debug with you?

**Comment by agracia-foticos** [comment]
I have made some progress, I have removed the reference to tailwind from my parent project, and I have added this in the project that I inherit as a module

`import { defineNuxtModule, installModule, createResolver } from '@nuxt/kit'
import { fileURLToPath } from 'node:url'

export default defineNuxtModule({
  meta: {
      name: '@design-system',
      compatibility: {
          nuxt: '^3.0.0'
      }
  },
  hooks: {
    'components:dirs'(dirs) {
      // Add ./components dir to the list
      dirs.push({
        path: fileURLToPath(new URL('./src/components', import.meta.url)),
        prefix: ''
      })
    }
  },
  async setup(options, nuxt) {
    const resolver = createResolver(import.meta.url)
    // It will add @nuxtjs/tailwindcss to the project
    await installModule('@nuxtjs/tailwindcss', {
      /**
       * Here, you specify where your config is.
       * By default, the module have a configPath relative
       * to the current path, ie the playground !
       * (or the app using your module)
       */
      cssPath: resolver.resolve('./src/styles/main.css'),
      configPath: resolver.resolve('./tailwind.config.js'),
      
    })
  }
})

Now i charge tailwind since the child module.

but now we have 2 css
![image](https://user-images.githubusercontent.com/77386602/226925116-6ed88f6a-9205-40e6-88ee-ccd85fa60971.png)
https://files.slack.com/files-pri/T1EEGTRBK-F0503QANWGZ/image.png
Why?

**Comment by ineshbose** [comment]
Would really need a replication at this point to see what's going on with what configuration (e.g., is the module added twice then?) or is it related to #621 or #531. If the issue still persists and you can provide a replication, please feel free to comment here and I'll reopen the issue.
