### ISSUE TITLE
missing `module.json`

### ISSUE THREAD

**Issue by danielroe** [nuxt-modules/tailwindcss#643]
### Version
@nuxtjs/tailwindcss: 6.6.2

### Reproduction Link

https://unpkg.com/browse/@nuxtjs/tailwindcss@6.6.2/dist/

### What is Expected?

There should be a `module.json` file present, which is referenced in `module.cjs`.

**Comment by yesworld** [comment]
Same problem :(

**Comment by Atinux** [comment]
Nice catch, reverted https://github.com/nuxt-modules/tailwindcss/commit/83ecb44bdf66e695f7edc8efaa4cd12729c45d5a

cc @manniL & @ineshbose 

The build was partially failing:
![CleanShot 2023-03-21 at 14.48.12@2x.png](https://volta.s3.fr-par.scw.cloud/Clean_Shot_2023_03_21_at_14_48_12_2x_c59edea50c.png)

**Comment by danielroe** [comment]
I've got a fix lined up.

**Comment by Atinux** [comment]
https://github.com/nuxt-modules/tailwindcss/releases/tag/v6.6.3

**Comment by Atinux** [comment]
Until you can ship a fix

**Comment by ineshbose** [comment]
Thanks for notifying - had some concerns with importing the tailwind stubs! Lesson learnt 😅
