### ISSUE TITLE
How do I replace the Tailwind colors with custom ones using a TypeScript interface?

### ISSUE THREAD

**Issue by smares** [nuxt-modules/tailwindcss#646]
Given I have an interface with custom colors just like how `DefaultColors` is defined in `tailwindcss/colors`:

```ts
export interface Colors {
  inherit: 'inherit'
  current: 'currentColor'
  transparent: 'transparent'
  black: '#000'
  white: '#fff'
  primary: {
    'DEFAULT': '#123456'
    '50': '#fff'
    '100': '#eee'
    ...
  }
}
```

How do I assign this to `tailwindConfig.theme.colors`?  I tried to `import type { Colors } from './myCustomColors'` then do `declare const colors: Colors` and eventually `tailwindConfig.theme.colors = colors`, but that gives me the error:

```
error TS2322: Type 'Colors' is not assignable to type 'ResolvableTo<RecursiveKeyValuePair<string, string>>'.
  Type 'Colors' is not assignable to type 'RecursiveKeyValuePair<string, string>'.
    Index signature for type 'string' is missing in type 'Colors'.
```

A stupid workaround I found was doing `tailwindConfig.theme.colors = { ...colors }` but that can't be the right way.

And obviously, I could simply export a plain object, but I am confused about the interface thing.

**Comment by ineshbose** [comment]
If your configuration corresponds to the `Colors` definition, the type for `theme.colors` should be an equivalent literal (check `.nuxt/tailwind.config.d.ts` when generated in your project). If not, what can I suggest is doing

```ts
declare module '#tailwind-config/theme/colors' {
  const colors: Colors;
  export default colors;
}

// then import like
import colors from '#tailwind-config/theme/colors';
```

(be sure to test this as I'm just sharing a scribbled thought here)

And yes, I would really discourage assigning to the config using `tailwindConfig.theme.colors = { ...colors }`.
