### ISSUE TITLE
Update Tailwind CSS to v3.3

### ISSUE THREAD

**Issue by kpdemetriou** [nuxt-modules/tailwindcss#649]
Tailwind CSS v3.3 introduces an array of useful utilities. It would be nice to see it supported in this module. As far as I understand this may just be a version bump, but I could be wrong.

**Comment by ExEr7um** [comment]
It also introduces support for TS syntax in config, so there is no need to transpile it by this module.

**Comment by P4sca1** [comment]
The docs for editor support may need to be updated. Also, the generated tailwind.config.cjs might no longer be needed (at least for editor support).

**Comment by P4sca1** [comment]
The docs for editor support may need to be updated. Also, the generated tailwind.config.cjs might no longer be needed (at least for editor support).

**Comment by ineshbose** [comment]
Thanks for mentioning that @P4sca1 - would you like to open a PR? 🙂

**Comment by P4sca1** [comment]
> Thanks for mentioning that @P4sca1 - would you like to open a PR? 🙂 

Yes, but I can't give an estimate on when I have the time and would like to test things first. So if anybody else is in the mood, then go for it 😀
Just noted it here quickly, so it doesn't get forgotten.

**Comment by P4sca1** [comment]
@ineshbose https://github.com/nuxt-modules/tailwindcss/pull/660
