### ISSUE TITLE
Referencing a default theme color in tailwind config through an alias isn't working

### ISSUE THREAD

**Issue by Freeptom** [nuxt-modules/tailwindcss#659]
Hi,

I've ran through the [setup guide](https://tailwindcss.nuxtjs.org/getting-started/setup) and can see tailwind classes being applied in my project e.g. `bg-yellow-500` produces a yellow background for an element. 

The issue I'm encountering is when I try to reference a provided theme color, giving it an alias like so (as described in the docs) inside of `tailwind.config.js`:

```
import defaultTheme from 'tailwindcss/defaultTheme'
export default {
  theme: {
    extend: {
      colors: {
        primary: defaultTheme.colors.green,
        secondary: "aliceblue"
      }
    }
  }
}
```

The secondary class works fine (simply referencing a color), but the primary one doesn't.

Please can someone let me know whether I'm missing something?
Thanks!

**Comment by Atinux** [comment]
Could you try with `import colors from 'tailwindcss/colors'` instead?
