### ISSUE TITLE
Base theme CSS not merging with parent theme

### ISSUE THREAD

**Issue by sadjow** [nuxt-modules/tailwindcss#664]
### Version
- @nuxtjs/tailwindcss: v6.6.6
- nuxt: v3.4.2

### Reproduction Link
- [CodeSandbox Example](https://codesandbox.io/p/sandbox/elegant-thompson-wiwsii?welcome=true)

### Steps to Reproduce
1. Set up an application using `@nuxtjs/tailwindcss` that extends a base theme, such as the "base-theme" demonstrated in the provided CodeSandbox link.
2. Ensure both the base theme and the parent theme include `assets/css/tailwind.css` files.
3. Notice that the `base-theme/assets/css/tailwind.css` file from the base theme is not taken into account.

### Expected Behavior
The application should merge the `base-theme/assets/css/tailwind.css` file from the base theme with the parent theme's `assets/css/tailwind.css` file.

### Actual Behavior
The application only loads the parent theme's `assets/css/tailwind.css` file, ignoring the `base-theme/assets/css/tailwind.css` file from the base theme.

**Comment by ineshbose** [comment]
There are a couple of things that can be considered.

1. We read the layer's cssPath file, and the app's cssPath, put the two together (with `\n` in between) in a new file using `addTemplate`, but this would be very fragile.
2. Create another template that has `@import "{cssPaths}"` for all layers through `postcss-import` - can't say the reliability of it with Tailwind for now, if you'd like to brainstorm & test, please do so 🙂
3. The styles in your reproduction can/should rather be added as Tailwind plugins into the configuration - see https://tailwindcss.com/docs/plugins#adding-utilities

Let me know how you solve it. I'll close this issue for now as it is believed to be out-of-scope.
