### ISSUE TITLE
ERROR  [postcss] If .class is a custom class, make sure it is defined within a @layer directive.

### ISSUE THREAD

**Issue by RomanSkrypnik** [nuxt-modules/tailwindcss#666]
Launching nuxt project each time facing this error message:
`The bg-preloader-gradient class does not exist. If bg-preloader-gradient is a custom class, make sure it is defined within a @layer directive.`

Error is shown only for one component. 
Other components which are using this class don't cause such message.
Removing this class from problem component solves problem but it's kinda weird.

Path to component:
`components/base/Table/Preloader.vue?vue&type=style&index=0&scoped=322d90a0&lang.scss:2:3:`

Component code:
<img width="555" alt="image" src="https://user-images.githubusercontent.com/44501848/234967571-48a4eb91-4796-4173-add6-369158c01c38.png">

**Comment by ineshbose** [comment]
A replication over Stackblitz would help!

But I would refer you to Tailwindcss docs about something similar - https://tailwindcss.com/docs/functions-and-directives#using-apply-with-per-component-css

**Comment by RomanSkrypnik** [comment]
Solved it by moving imports of scss to top level
