### ISSUE TITLE
New v6.6.7 broke Tailwind CSS IntelliSense

### ISSUE THREAD

**Issue by sdsoldi** [nuxt-modules/tailwindcss#668]
### Version
@nuxtjs/tailwindcss: 6.6.7
nuxt: 3.4.3

### Steps to reproduce
In vscode with the extension:
https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss
With "@nuxtjs/tailwindcss": "6.6.6" = Works fine and suggest classes
With "@nuxtjs/tailwindcss": "6.6.7" = Crash and not work

### What is Expected?
Suggest classes of tailwindcss

### What is actually happening?
Is crashing on build in tailwind css intellisense
```
[.nuxt\tailwind.config.cjs] Initializing...
[.nuxt\tailwind.config.cjs] Loaded Tailwind CSS config file: /.nuxt/tailwind.config.cjs
[.nuxt\tailwind.config.cjs] Loaded postcss v8.4.23: \node_modules\postcss
[.nuxt\tailwind.config.cjs] Loaded tailwindcss v3.3.2: \node_modules\tailwindcss
[.nuxt\tailwind.config.cjs] Building...
[Error - 4:49:52 PM] Tailwind CSS: Cannot read properties of undefined (reading 'includes')
TypeError: Cannot read properties of undefined (reading 'includes')
    at \node_modules\tailwindcss\lib\lib\setupContextUtils.js:824:81
    at Array.some (<anonymous>)
    at registerPlugins (\node_modules\tailwindcss\lib\lib\setupContextUtils.js:824:46)
    at createContext (\node_modules\tailwindcss\lib\lib\setupContextUtils.js:1178:5)
    at Object.module (\.vscode\extensions\bradlc.vscode-tailwindcss-0.9.11\dist\tailwindServer.js:2960:6934)
    at \.vscode\extensions\bradlc.vscode-tailwindcss-0.9.11\dist\tailwindServer.js:2960:11208
    at Generator.next (<anonymous>)
    at i (\.vscode\extensions\bradlc.vscode-tailwindcss-0.9.11\dist\tailwindServer.js:1:1077)
```

npm-why tailwindcss in both versions of 6.6.6 and 6.6.7 is using > @nuxtjs/tailwindcss > tailwindcss@3.3.2

**Comment by ineshbose** [comment]
I'm using 6.6.7 with the extension on Windows and it seems to be working. Could I get more some information about your system possibly? `.nuxt/tailwind.config.cjs` is under consideration of being removed anyway due to ESM/TS support in Tailwind 3.3 - maybe you could test without specifying config location for your extension as that?

**Comment by sdsoldi** [comment]
In .nuxt/tailwind.config.cjs is generating

```
"safelist": [
    {
      "pattern": {}
    },
    {
      "pattern": {}
    }
  ],
```

Plugin crashes on check.pattern.source.includes("!"). Source is not defined in empty patterns.

In /tailwind.config.ts I have 

```
safelist: [
    {
      pattern: /max-w-(md|lg|xl|2xl)/,
    },
    {
      pattern:
        /bg-(yellow|orange|gray)-(50|100|200|300|400|500|600|700|800|900|950)/,
    },
  ],
```
If I remove safelist, works.

**Comment by Atinux** [comment]
Could you try the v6.6.8?

**Comment by sdsoldi** [comment]
Fixed
