### ISSUE TITLE
Object notation for tailwind content configuration is currently not supported

### ISSUE THREAD

**Issue by art-boer** [nuxt-modules/tailwindcss#671]
### Is your feature request related to a problem? Please describe.
In one of our projects we would like to be able to use relative paths, within, the tailwind content configuration see: https://tailwindcss.com/docs/content-configuration#using-relative-paths

Trying to use object notation is not supported by the nuxt module, since it expects an array and will crash if being used like in the tailwind docs code snippet above.

### Describe the solution you'd like
It would be great if we could also use the object notation for the content configuration in the tailwind config file, so we can enable relative paths.

**Comment by ineshbose** [comment]
Thank you for opening an issue. This came to my notice as well and I'll look into having this implemented soon (unless you're willing to make a PR 🙂).

I do want to ask - in this case, when using object configuration, would you want the default paths to merge with `content.files` or completely override (which I can see people leaning for)? Also on Tailwind's docs, they mention "This will likely become the default behavior in the next major version of the framework", but this merely be a consideration I think.

You should be able to take advantage of the `defuFn` as a workaround doing:
```ts
  content: () => ({
    relative: true,
    files: [
      './pages/**/*.{html,js}',
      './components/**/*.{html,js}',
    ],
  }),
```

**Comment by ineshbose** [comment]
Object syntax is nowhere to go it seems (considering all the properties, breaking changes, etc) - https://github.com/tailwindlabs/tailwindcss/pull/9396/files#diff-19584312cba053f9726eeb4b0766364b873cd974e552656c557ae30ee45f9d00 - so the module should support `content` as object. 🙂
