### ISSUE TITLE
[BUG] Tailwind CSS IntelliSense vscode's extension not longer supported since v6.6.8

### ISSUE THREAD

**Issue by LouisMazel** [nuxt-modules/tailwindcss#677]
### Version
@nuxtjs/tailwindcss: v6.6.8
nuxt: v3.4.3

### Reproduction Link

Impossible

### Steps to reproduce

You should set your tailwind configuration directly in the `nuxt.config.js` (so, you don't have a `tailwind.config.js` file in the root folder)

- Upgrade the version of `@nuxtjs/tailwindcss` to `v6.6.8`
- Run `pnpm install`
- The script postinstall `nuxi prepare` is executed
- The config file `.nuxt/tailwind.config.cjs` disappears
- Then, the extension Tailwind CSS IntelliSense doesn't work anymore

### What is Expected?

Have Tailwind CSS autocompletion in VS Code with Tailwind CSS IntelliSense. 

### What is actually happening?

The extension no longer works because the `tailwind.config.cjs` is no longer generated.

---

So, the complete support of the editor, therefore, needs this file, contrary to the description of this PR: https://github.com/nuxt-modules/tailwindcss/pull/660

**Comment by ineshbose** [comment]
Hi, this is correct - please read https://github.com/nuxt-modules/tailwindcss/issues/531#issuecomment-1277539649

**Comment by LouisMazel** [comment]
@ineshbose Yes, but I prefer to have another solution than to re-create a file at the root of the project

**Comment by ineshbose** [comment]
Yes, you have two options:

1. Move config as `tailwind.config` at root of project (you don't prefer this)
2. Define a module as displayed in docs to keep `tailwind.config.cjs` in the `.nuxt` directory

Beyond these options, the module is likely to not have any functionality for this.
