### ISSUE TITLE
There are no syntax prompts in webstorm anymore

### ISSUE THREAD

**Issue by imyuanli** [nuxt-modules/tailwindcss#678]
### Version
@nuxtjs/tailwindcss: 
nuxt:

**Comment by imyuanli** [comment]
I don't often use nuxt, but I have installed the "@ nuxtjs/tailwindcss" module, and the tailwind style can take effect. However, my webstorm doesn't have any code prompts. Is it because my project doesn't have tailwind.config.ts?

**Comment by imyuanli** [comment]
Sure enough, after I added the tailwind configuration file, the code prompt appeared. Which of the tailwind configuration items, tailwindcss.comnfig.ts and nuxt.config.ts, has higher priority, or will they be merged?

**Comment by ineshbose** [comment]
`tailwind.config.ts` has higher priority, but it would be ideal to point it to `.nuxt/tailwind.config.cjs`.
