### ISSUE TITLE
Can't resolve #build/tailwind.config/*

### ISSUE THREAD

**Issue by simllll** [nuxt-modules/tailwindcss#680]
### Version
@nuxtjs/tailwindcss: 6.7.0
nuxt: v2.16.3

### Steps to reproduce
installing @nuxtjs/tailwindcss 6.7.0 or any version abover 6.6.7 and run nuxt build on a nuxt2 project, it results into build errors like the following:

Module not found: Error: Can't resolve '#build/tailwind.config/variants.mjs' in '/home/simon/Dev/hokify/hokify-server/services/admin-app/admin-interface/.nuxt/tailwind.config'
it throws errors about each file mentioned inside of tailwind.config/index.mjs

### What is Expected?
should build like < 6.6.8

### What is actually happening?
throws errors during build that it cannot find #build/tailwind.config/...
the files are there, but not sure abuot "#build" itself?
![image](https://github.com/nuxt-modules/tailwindcss/assets/5757263/972463c8-552a-4f7d-8f92-dad4ffe49853)

**Comment by simllll** [comment]
Can't see anything that leads to this in the changeset: https://github.com/nuxt-modules/tailwindcss/compare/v6.6.7...v6.6.8

did anythign else change? e.g. building/packaging?

**Comment by ineshbose** [comment]
The resolved `tailwind.config.cjs` did stop being generated, but this seems to be related #616 which was released in 6.4.1

**Comment by simllll** [comment]
Would fit indeed to the error, but 6.6.6 and 6.6.7 are working. Indeed strange, I'm trying to create a replica on stackblitz.

**Comment by simllll** [comment]
I'm not able to reproduce it somehow on stacklitz, maybe it is related to our monorepo setup (pnpm) which hoists all the nuxt speicifc things, but maybe it's missing something... still strange that it works with `< 6.6.8`.

will try to followup on this later

**Comment by ineshbose** [comment]
Sure. Here to help - let me know 🙂

**Comment by simllll** [comment]
I finally was able to reproduce the issue, it's not realted to pnpm, it happens when I import theme.
import { theme } from '#tailwind-config';

i created a simple helpers/test.ts:
```
import { theme } from '#tailwind-config';

export function blub() {
  return theme.colors['color-blue-dark'];
}

```

and imported it inside pages/index.vue to do just a simple console log on mounted of "blub()".

then I get the same erros: 
```
ERROR in ./.nuxt/tailwind.config/index.mjs
Module not found: Error: Can't resolve '#build/tailwind.config/blocklist.mjs' in '/home/projects/github-ruub1l-bhwdqo/.nuxt/tailwind.config'

```
see https://stackblitz.com/edit/github-ruub1l-bhwdqo?file=pages%2Findex.vue,package.json,helpers%2Ftest.ts

**Comment by simllll** [comment]
Reduced it to the minimum changes: https://stackblitz.com/edit/github-ruub1l-ssfjxw?file=README.md
(no typescript, just tailwind and the import error)

**Comment by ineshbose** [comment]
Okay! I'm able to now find the issue.
I was puzzled about this issue not happening below 6.6.8 as you noted, but we also noted that we dropped `tailwind.config.cjs` for the new versions which created issues for Nuxt 2 as we were unable to test it, and `exposeConfig` in Nuxt 2 relies on it for CommonJS, while the `#build/tailwind.config/*` is for `exposeLevel` tree-shaking (but I can't say if Nuxt 2 can take advantage of it).

While I plan a fix for this ASAP, if you wish to stay on the latest version, the workaround for this, as in the [docs](https://tailwindcss.nuxtjs.org/tailwind/editor-support/), is to create a module and add it before `@nuxtjs/tailwindcss` in Nuxt config:
```js
import { addTemplate } from '@nuxt/kit'

export default function () {
  this.nuxt.hook('tailwindcss:resolvedConfig', (c) => 
    addTemplate({
      filename: 'tailwind.config.cjs',
      getContents: () => `module.exports = ${JSON.stringify(c)}`,
      write: true
    })
  )
}
```
