### ISSUE TITLE
Some css declarations (colors) appear twice

### ISSUE THREAD

**Issue by woldtwerk** [nuxt-modules/tailwindcss#685]
### Version
@nuxtjs/tailwindcss: 
nuxt: 

### Reproduction Link

https://codesandbox.io/s/stoic-panka-vf2kk8?file=/components/TButton.vue

### Steps to reproduce
inspect the button:
![image](https://github.com/nuxt-modules/tailwindcss/assets/32794633/20a9b753-0144-4469-a1c3-b4b99e5114d5)

### What is Expected?
css background/color declarations should only appear once:
```css
background-color: rgb(59 130 246 / var(--tw-bg-opacity));
```
### What is actually happening?
they appear twice:
```css
background-color: rgb(59 130 246 / 1);
background-color: rgb(59 130 246 / var(--tw-bg-opacity));
```

**Comment by mrleblanc101** [comment]
That's the fallback for browser that don't support variable inside rgb function

**Comment by ineshbose** [comment]
> That's the fallback for browser that don't support variable inside rgb function

Thanks for providing input on this. I'm curious why this is happening with the module and not vanilla tailwindcss..

**Comment by woldtwerk** [comment]
> That's the fallback for browser that don't support variable inside rgb function

which browsers are we talking about? 
I think it shouldn't differ from tailwinds default behavior.

**Comment by mrleblanc101** [comment]
This is probably your PostCSS/Autoprefixer config.
