### ISSUE TITLE
How make other postcss plugins affect on tailwind classes

### ISSUE THREAD

**Issue by alihardan** [nuxt-modules/tailwindcss#687]
Hello. Here is my nuxt.config:

```ts

export default defineNuxtConfig({
  modules: ["@nuxt/content", "@nuxtjs/tailwindcss"],
  postcss: {
    plugins: { "postcss-rtlcss": {} },
  },
});

```

I have included postcss `postcss-rtlcss` plugin. it affects on my own defined CSS classes (makes `[dir="rtl"]` mode for each class), but not on tailwind classes. am I missing something?

Thanks.

**Comment by ineshbose** [comment]
Hi, your existing postcss configuration should not be affected (https://github.com/nuxt-modules/tailwindcss/blob/255da816049f62ffbd9ce7bb0d3dd0c750793cb1/src/module.ts#L228) - is there something happening that you don't expect?

**Comment by alihardan** [comment]
@ineshbose, my question is how to make postcss plugins affect tailwind classes. When I use `postcss-rtlcss` plugin, it generates rtl CSS for each CSS selector. but not works on tailwind classes.

current generated CSS:

```css
.ml-6 {
  margin-left: 1.5rem;
}
```

But I expect the below, because I used `postcss-rtlcss` plugin:

```css

[dir="rtl"] .ml-6 {
  margin-right: 1.5rem;
}

```

**Comment by ineshbose** [comment]
I see what you mean!
I think in this case, you're possibly looking for a Tailwind plugin rather than PostCSS plugin. On some digging, there's this discussion - https://github.com/tailwindlabs/tailwindcss/discussions/1492

**Comment by alihardan** [comment]
@ineshbose, Thanks but the question is how make PostCSS plugin affect, I know about that Tailwind plugin. When I use this PostCSS plugin + Tailwind on a Vite + Vue project, it works and generates what I expect for tailwind classes. but not on this nuxt module.

**Comment by ineshbose** [comment]
@alihardan the module configuration should work same as you use Tailwind - if it's not working as desired, please provide a reproduction over Stackblitz and we'll be able to investigate this! :)

**Comment by alihardan** [comment]
> @alihardan the module configuration should work same as you use Tailwind - if it's not working as desired, please provide a reproduction over Stackblitz and we'll be able to investigate this! :)

I made a reproduction over Stackblitz that shows the unexpected behavior. As you see in this reproduction, postcss plugin affects my `.test` class, but not the tailwind `ml-4` class.

https://stackblitz.com/edit/nuxt-starter-ckqtyt?file=app.vue

**Comment by ineshbose** [comment]
Thanks for the repro 🙂 

It seems likely that even though we're using object-syntax for PostCSS plugins instead of array, the order of assignment for object-property is still being followed. So `postcss-rtlcss` is installed before `tailwindcss` (as a pcss plugin).

The workaround for this, in your `nuxt.config`, is:

```diff
// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  modules: ['@nuxtjs/tailwindcss'],
  postcss: {
-   plugins: { 'postcss-rtlcss': {} },
+   plugins: {
+      tailwindcss: {},
+      autoprefixer: {},
+      'postcss-rtlcss': {}
+    },
  },
});
```
