### ISSUE TITLE
Can't use tailwindcss since last release. (WARN  Module @nuxtjs/tailwindcss is disabled due to incompatibility issues: - [bridge] Nuxt bridge is required)

### ISSUE THREAD

**Issue by vahid-bagh3ri** [nuxt-modules/tailwindcss#693]
### Environment

  System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
    Memory: 4.30 GB / 15.78 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.23.0-20220130.1630 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (114.0.1823.51)
    Internet Explorer: 11.0.19041.1566

### Reproduction

https://stackblitz.com/edit/github-veimfs

### Describe the bug

I deployed the same version of my packages two days ago, but today it gives me this err:

 **WARN  Module @nuxtjs/tailwindcss is disabled due to incompatibility issues: - [bridge] Nuxt bridge is required**

I will send some important packages that I use:
```js
"dependencies": {
    "@tailwindcss/line-clamp": "^0.4.0",
    "nuxt": "^2.16.1",
    "vue": "^2.7.0",
    "webpack": "^4.46.0"
},
"devDependencies": {
    "@nuxtjs/tailwindcss": "^6.4.0",
    "postcss": "^8.4.5",
    "@babel/eslint-parser": "^7.16.3",
},
"resolutions": {
    "@nuxt/kit": "3.0.0-rc.13"
}

```

### Additional context

At this moment I can't use nuxt-bridge is there any other solution for it?

**Comment by Atinux** [comment]
Cc @ineshbose

**Comment by mattiaserdfeld** [comment]
Had the same issue right now. Build just failed today but we specifed older version. Version v6.8.0 was released last week but that caused the issue.

Try
`"@nuxtjs/tailwindcss": "6.7.2",` without the ^

**Comment by ineshbose** [comment]
I misunderstood [`NuxtCompatibility` configuration](https://github.com/nuxt/nuxt/blob/5f5b9dfe99fdc3f45e224eee496032ae982d897b/packages/schema/src/types/compatibility.ts#L16) and thought that `bridge: true` means that bridge is allowed - sorry! Pushed fix to main (c488680ec556d8fcd596ec28b0be0223e21b9bb1, again sorry for direct commit by mistake!) - @Atinux if you'd like to release this fix.

**Comment by Shooteger** [comment]
I have the same issue. With newest Nuxt 2 (2.17.0), Tailwind breaks starting with 6.8.0
I use now Tailwind 6.7 and default Nuxt 2.17 and everything works fine:

`"@nuxtjs/tailwindcss": "6.7.0",`

Works for Nuxt 2.16.3 too

**Comment by PawelDmochowski** [comment]
Hi @Atinux,

Thanks for all great work you put into this project!
Is there any chance the fix by @ineshbose is released soon?

**Comment by serkon** [comment]
I encountered the same error, but after changing the versions of these packages, it was resolved.

"@nuxtjs/tailwindcss": "^5.3.3",
"postcss": "^8.4.17",

**Comment by ineshbose** [comment]
> > I misunderstood [`NuxtCompatibility` configuration](https://github.com/nuxt/nuxt/blob/5f5b9dfe99fdc3f45e224eee496032ae982d897b/packages/schema/src/types/compatibility.ts#L16) and thought that `bridge: true` means that bridge is allowed - sorry! Pushed fix to main ([c488680](https://github.com/nuxt-modules/tailwindcss/commit/c488680ec556d8fcd596ec28b0be0223e21b9bb1), again sorry for direct commit by mistake!) - if you'd like to release this fix.
> 
> So if I understand correctly, Nuxt2 with bridge is not compatible with this module?

It is compatible. The latest releases should work fine!

**Comment by valh1996** [comment]
> It is compatible. The latest releases should work fine!

```
> nuxi dev

Nuxt 2.17.2-28284499.5674f49 with Nitro 2.7.2                                                                                                                14:38:56
                                                                                                                                                             14:38:57
  ➜ Local:    http://localhost:3000/
  ➜ Network:  use --host to expose

ℹ @nuxt/postcss8 is disabled since nuxt has upgraded to postcss v8.                                                                                         14:39:00
ℹ Module meta took 3.59ms to setup.                                                                                                                         14:39:00
ℹ Module nuxt-bridge took 24.3ms to setup.                                                                                                                  14:39:00

 WARN  Module @nuxtjs/tailwindcss is disabled due to incompatibility issues:                                                                                 14:39:01
 - [bridge] Nuxt bridge is not supported

ℹ Module imports took 1.97ms to setup.                                                                                                                      14:39:01

 WARN  [bridge] Detected module incompatibility issues for @nuxtjs/tailwindcss:                                                                              14:39:01
 - [bridge] Nuxt bridge is not supported
```
I don't understand since I have the latest version:
```
@nuxtjs/tailwindcss@6.9.4
@nuxt/bridge-edge@3.0.0-rc.2-28317515.f225b80
```

**Comment by ineshbose** [comment]
Thanks for pointing it out. I suppose leaving bridge option as `undefined` will be the way; will create a fix release soon!

**Comment by valh1996** [comment]
> Thanks for pointing it out. I suppose leaving bridge option as `undefined` will be the way; will create a fix release soon!

Ok thank you. Do you have a workaround in the meantime?

**Comment by yshrsmz** [comment]
@ineshbose hi, I see you added a new change to remove `bridge` option( https://github.com/nuxt-modules/tailwindcss/commit/58abedf5e5f84edfcc3d2a2f257e3d7d89969fee ).

Could you publish a new release 🙏 ?

**Comment by ineshbose** [comment]
> @ineshbose hi, I see you added a new change to remove `bridge` option( [58abedf](https://github.com/nuxt-modules/tailwindcss/commit/58abedf5e5f84edfcc3d2a2f257e3d7d89969fee) ).
> 
> Could you publish a new release 🙏 ?

Released

**Comment by yshrsmz** [comment]
@ineshbose 

Thanks, but I can't see the new release 🤔 
https://www.npmjs.com/package/@nuxtjs/tailwindcss?activeTab=versions

Also, the latest release is named `v6.9.6` while the corresponding tag is `v6.9.5`
https://github.com/nuxt-modules/tailwindcss/releases/tag/v6.9.5
