### ISSUE TITLE
Static assets in background-image won't work in prod mode

### ISSUE THREAD

**Issue by mrleblanc101** [nuxt-modules/tailwindcss#694]
### Version
@nuxtjs/tailwindcss: 6.7.2
nuxt: 3.5.2

### Steps to reproduce
This will work in dev mode, but not in prod mode.
In prod mode you will get a 404 since the assets is not extracted.
`class="bg-[url('@/assets/img/bubbles-nav.png')]"`

### What is Expected?
This should also work in prod mode.

### What is actually happening?
Vite doesn't extract the assets, so you need to move the image in `public/` and remove the `@/`

**Comment by mrleblanc101** [comment]
From what I understand, this is expected as Vite can't extract the assets so either it shouldn't work in dev mode or there should be a warning in the console, no ? Otherwise you're only gonna find out when you do a production build.

**Comment by ineshbose** [comment]
Hi, yes you are right. This wouldn't be feasible in production. You could import the path to the file and pass that into `bg-[${path}]` theoretically, but then tailwind JIT won't be able to parse it. You can move it into public, or as I mentioned, import the path to the file and then use inline CSS.

**Comment by mrleblanc101** [comment]
Don't you think it would be possible to detect and warn against this ?
It should at the very least be in the docs so people don't get cought as it work in dev mode (probably because Vite serve the static folder in dev mode)

**Comment by ineshbose** [comment]
Again, my feeling is that it's not a module problem though. You can use vanilla JS with Vite or even Webpack, and assets are handled different to public/static files, so it wouldn't work there as well.. 😅

**Comment by mrleblanc101** [comment]
Well it work in sass...
`background-image: url("~assets/img/bubbles-nav.png");`

**Comment by ineshbose** [comment]
Yes. That will work as it is picked up by Vite and SASS loader - not under the scope of Tailwind!

**Comment by mrleblanc101** [comment]
It would also work in vanilla js using a :style binding. So you agree there should be a warning in the doc or a build time/runtime warning ?

**Comment by ineshbose** [comment]
Yes it would work with a style binding, as I convey in my first message on the thread about using inline style over Tailwind classes.

I'm unable to agree as I can't see where this could fit in the documentation of this module..

**Comment by mrleblanc101** [comment]
Yeah, I'm more into doing a build time warning in the console anyway. I just saw you edit to your first message. If you find this is a good improvement, i guess I'm just surprised as to why you closed the issue.
