### ISSUE TITLE
Merge tailwind.config.ts

### ISSUE THREAD

**Issue by Dominic-Marcelino** [nuxt-modules/tailwindcss#696]
### Version
@nuxtjs/tailwindcss: ^6.8.0
nuxt: 3.6.0

### Steps to reproduce
- Create a projectOne with a `tailwind.config.ts`
- Create a projectTwo that extends projectOne
- Create a `tailwind.config.ts` in projectTwo

### What is Expected?
The configs should be merged

### What is actually happening?
The second config is overriding the first one

Using the config inside `nuxt.config` it get's merged as expected.

**Comment by ineshbose** [comment]
Hi, this is expected behaviour. projectOne is a layer while projectTwo is your main Nuxt project - that is given precedence and then missing defaults are filled in from projectOne (using defu). Did you expect overriding/reading the other way around? (it could mean that filling values in projectTwo - your main app - would be useless)

**Comment by Dominic-Marcelino** [comment]
Sorry, didn't described the actual behaviour very precisely. 

> missing defaults are filled in from projectOne (using defu)

That's excactly what I'm expecting to happen. When using the nuxt.config it works and gets merged. 
But when I do create a dedicated `tailwind.config.ts` file those doesn't get merged. Example:

```ts
// projectOne/tailwind.config.ts
export default <Partial<Config>>{
   prefix: 'tw-',
   theme: {
     extend: {
       colors: {
         primary: '#4e67aa',
       }
     }
   }
 }
```
```ts
// projectTwo/tailwind.config.ts
export default <Partial<Config>>{
  prefix: 'tw-', // NOTE: already need to re-add the prefix here, as it doesn't get merged from projectOne
  theme: {
    extend: {
      colors: {
        secondary: '#FFC0CB',
      }
    }
  }
}
```

In this case only `projectTwo/tailwind.config.ts` will be used. Inside of projectTwo the primary color will be unknown and I also need to re-add the prefix.

**Comment by ineshbose** [comment]
I'm unable to replicate this, are you sure you're configuring properly?

Using the repository playground - https://stackblitz.com/github/nuxt-modules/tailwindcss?file=playground%2Ftheme%2Ftailwind.config.cjs

I copy the config of `projectOne/tailwind.config.ts` into `playground/theme/tailwind.config.cjs` and the config from `projectTwo/tailwind.config.ts` into `playground/tailwind.config.ts` and in the playground viewer, the prefix and primary & secondary colors merge. If that's not the case with yours, would you be able to provide a reproduction?

**Comment by Dominic-Marcelino** [comment]
Thanks for checking!

I haven't been able to replicate it in a clean project. After further debugging it turned out that projectOne included an unresolved config-path what has caused the issue: 

```ts
export default defineNuxtConfig({
  tailwindcss: {
    configPath: './tailwind.config.ts',
  }
}
```

After adding a resolver everything works as expected:
```ts
import { createResolver } from '@nuxt/kit';
const { resolve } = createResolver(import.meta.url);

export default defineNuxtConfig({
  tailwindcss: {
      configPath: resolve('./tailwind.config.ts'),
  }
}
```
