### ISSUE TITLE
Move from tailwindcss-dark-mode

### ISSUE THREAD

**Issue by onurusluca** [nuxt-modules/tailwindcss#697]
[tailwindcss-dark-mode](https://github.com/ChanceArthur/tailwindcss-dark-mode) is not maintained anymore. It would be much better that this is removed from the docs and that a way added to use the built in dark mode detector.

Version that added darkmode to Tailwind:
https://tailwindcss.com/blog/tailwindcss-v2

Related documentation page:
https://tailwindcss.nuxtjs.org/examples/dark-mode/

**Comment by ineshbose** [comment]
Thanks! Will update ASAP, but PR is also very welcome for this. 😊

**Comment by Atinux** [comment]
Weird because I updated it two weeks ago to use the latest version: https://tailwindcss.nuxtjs.org/examples/dark-mode

**Comment by Atinux** [comment]
I only need to remove the first sentence which is outdated.

**Comment by onurusluca** [comment]
@Atinux Appreciate it!
