### ISSUE TITLE
@nuxtjs/i18n 8.0.0 generate bug

### ISSUE THREAD

**Issue by JoGlows** [nuxt-modules/tailwindcss#698]
### Version
  "devDependencies": {
    "@nuxt/devtools": "latest",
    "@nuxtjs/tailwindcss": "^6.8.0",
    "@types/node": "^18",
    "nuxt": "^3.6.1",
    "@nuxtjs/i18n": "^8.0.0-beta.12"
  },

### Node Version
       16.14.0

### Steps to reproduce
if I generate project,it will not access tailwindcss style
<img width="668" alt="螢幕截圖 2023-06-30 下午5 54 11" src="https://github.com/nuxt-modules/tailwindcss/assets/129497217/dbd6a3d5-3de9-4fa8-8599-9df360ef1ba8">
<img width="432" alt="螢幕截圖 2023-06-30 下午5 54 23" src="https://github.com/nuxt-modules/t
<img width="868" alt="螢幕截圖 2023-06-30 下午5 54 53" src="https://github.com/nuxt-modules/tailwindcss/assets/129497217/efa5b7c7-a0b0-4232-af57-6ae4d940236e">
ailwindcss/assets/129497217/648e504f-00c3-42da-ac3a-6ce6e6a600e9">

### What is Expected?
**When I remove ``` vueI18n: './i18n.config.ts'```  and i18n.config.ts file, that's working!!**
<img width="912" alt="螢幕截圖 2023-06-30 下午5 57 06" src="https://github.com/nuxt-modules/tailwindcss/assets/129497217/bb83ee59-2e53-44cd-8d1b-1aafb9390230">

### What is actually happening?
How can fix?? it's bug?

**Comment by Slimpak** [comment]
@JoGlows I have this bug also, is there a solution?

**Comment by luca-smartpricing** [comment]
The fix was:

```js
export default defineNuxtConfig({
  experimental: {
    inlineSSRStyles: false
  }
})
```

I think this fix break the tailwind plugin
https://github.com/nuxt/nuxt/pull/21573
