### ISSUE TITLE
Content path with layer alias can't be resolved

### ISSUE THREAD

**Issue by Dominic-Marcelino** [nuxt-modules/tailwindcss#703]
### Version
@nuxtjs/tailwindcss: 6.8.0
nuxt: 3.6.1

### Reproduction Link
https://stackblitz.com/edit/nuxt-starter-liwga9?file=layerTwo%2Ftailwind.config.ts,layerTwo%2Fnuxt.config.ts,layerTwo%2Fcomponents-overrides%2FlayerOne%2FTestButton2.vue

1. install node-modules in both projects (`layerOne` and `layerTwo`)
2. Start the layers
3. View layer-two preview: The tailwind-class used in `components-overrides/layerOne/TestButton2.vue` won't be recognized

### Steps to reproduce
- Create two nuxt projects: `layerOne` and `layerTwo`
- `layerTwo` extends `layerOne`
- Add nuxt-tailwind
- Add an alias for the layer to nuxt-config
- Add a new content-path in the `layerTwo` tailwind-config including the layer-alias as a path

### What is Expected?
- I'd expect the alias to work

### What is actually happening?
- The alias isn't working
- Using a relative path instead works

As an alternative to the layer-alias it also would be possible to use an resolver. This would be related to: https://github.com/nuxt-modules/tailwindcss/issues/701

**Comment by Dominic-Marcelino** [comment]
Any update on this?

**Comment by ineshbose** [comment]
Can you check if 6.9.0 makes improvements on this please?

**Comment by Dominic-Marcelino** [comment]
In my setup the custom content-paths seems to be fully auto-detected now. But from what I've been able to test it seems to work now 👍🏼
