### ISSUE TITLE
`nuxt dev` command should be `npm run dev`

### ISSUE THREAD

**Issue by rowild** [nuxt-modules/tailwindcss#705]
Here
[tailwind.config.js](https://tailwindcss.nuxtjs.org/getting-started/setup#tailwind-files)
right under the header it says

When running `nuxt dev` ...

There is no `nuxt dev`. Should this be `npm dev` instead? 
Or `npm nuxi dev`?

**Comment by Atinux** [comment]
It should be `npm run dev`
