### ISSUE TITLE
Enable exporting the statically-rendered config viewer

### ISSUE THREAD

**Issue by obulat** [nuxt-modules/tailwindcss#706]
### Is your feature request related to a problem? Please describe.

The Tailwind config viewer cannot be exported to be published on a static website.

### Describe the solution you'd like

Add the [`export`](https://github.com/rogden/tailwind-config-viewer#export) command from TCV to this module. This would build the viewer and publish it to a directory that can be copied to a static site.

### Describe alternatives you've considered

This could be implemented as a separate command, or as an option to the module. 

### Additional context

We publish the Tailwind config viewer on our static documentation site (https://docs.openverse.org/tailwind/) using TCV's [`export`](https://github.com/rogden/tailwind-config-viewer#export). TCV does not support TS version of Tailwind config, so we tried to move to this module.

**Comment by Atinux** [comment]
Sorry for the late answer @obulat 

I guess we could guess we could add the `exportTailwindViewer: false|true` option and hook into `nuxt generate` command to do the same thing as https://github.com/rogden/tailwind-config-viewer/blob/master/cli/export.js

Are you using `nuxt generate` for your app?

**Comment by ineshbose** [comment]
> I guess we could guess we could add the `exportTailwindViewer: false|true` option

If #691 is implemented, it should also allow cleaner configuration! 🙂

**Comment by obulat** [comment]
> Sorry for the late answer @obulat 
> 
> I guess we could guess we could add the `exportTailwindViewer: false|true` option and hook into `nuxt generate` command to do the same thing as https://github.com/rogden/tailwind-config-viewer/blob/master/cli/export.js
> 
> Are you using `nuxt generate` for your app?

It would be awesome, @Atinux .
We use `nuxt build` for the app, but we use a separate command do build and copy the config viewer. So, we could use the `generate` command just for building the viwer.

**Comment by gekkedev** [comment]
I suppose the export command could be supported with a similar interface to [`nuxt build --analyze`](https://v2.nuxt.com/docs/configuration-glossary/configuration-build/#analyze) (accessible through the regular build command).

However, as long as this wrapper module is installed, the [config viewer's export functionality](https://github.com/rogden/tailwind-config-viewer#export) is directly accessible if you do not mind maintaining your `tailwind.config` in JS (which AFAIK is also required by IDE plugins like _TWCSS Intellisense_?):
```js
#Yarn
yarn tailwind-config-viewer export -c specify/your/tailwind.config.js
#NPM
npm tailwind-config-viewer export -c specify/your/tailwind.config.js
```
Even the argument `-c ` can be left out if the config file is in the default location. If support gets added to this module, the path could be read from the `nuxt.config` instead to reduce redundancy.

**Comment by ineshbose** [comment]
@obulat let me know if the newest addition helps out in your process; feedback would be greatly appreciated!

**Comment by obulat** [comment]
> @obulat let me know if the newest addition helps out in your process; feedback would be greatly appreciated!

Thank you for this addition! I've opened an issue in Openverse to track this.
