### ISSUE TITLE
Include Tailwind version in docs

### ISSUE THREAD

**Issue by nicklassandell** [nuxt-modules/tailwindcss#712]
Would be very nice to be able to tell which Tailwind version this module is using, without having to dig through the release log (which may or may not be reliable).

It would also be nice to know roughly how often it is updated, .i.e. if is it tied to feature versions of tailwind or if are there occational updates for minor versions too. It's currently 3 minor versions behind (currently 3.3.0 according to release log), and it was the cause of an issue I was having, hence digging into this.

Also: big thanks for the putting in the work on this module!

**Comment by ineshbose** [comment]
Hi, thanks for opening an issue and reporting your feedback. I really do agree with you and we're looking into formalising releases (and even setting up edge releases) - stay tuned!
