### ISSUE TITLE
Reference tailwind config in nuxt.config.ts

### ISSUE THREAD

**Issue by codeflorist** [nuxt-modules/tailwindcss#719]
Is it possible to reference the tailwind config in `nuxt.config.ts`?

If i put `import { theme } from '#tailwind-config'` in `nuxt.config.ts` it throws the error `Cannot find module '#tailwind-config'`.

**Comment by ineshbose** [comment]
That is not possible... it can only be referenced in runtime of your application. It wouldn't make sense to do this, but if you have a separate configuration file, you could import that into your `nuxt.config`.

**Comment by codeflorist** [comment]
@ineshbose Thans a lot! I probably could have tought of that myself 😄

This is working nicely:
```js
import { theme } from './tailwind.config.js'
```
