### ISSUE TITLE
use tailwindcss text-[#dfdfdf] in @nuxt/content's markdown file, not work

### ISSUE THREAD

**Issue by klren0312** [nuxt-modules/tailwindcss#721]
the hex color string becomes an id
![1695102564342](https://github.com/nuxt-modules/tailwindcss/assets/10903843/dae094c5-9b4d-436b-8d80-f32bdc7dba69)

**Comment by Atinux** [comment]
Might be related to MDC, cc @farnabaz

**Comment by ineshbose** [comment]
@klren0312 could you please share the source notation in your markdown (`.md`) file for this please?

**Comment by klren0312** [comment]
add this to markdown file
```markdown
::p{.text-lg .leading-8 .text-[#dddddd]}
testtesttest testtesttest
::
```

**Comment by ineshbose** [comment]
Unfortunately this wouldn't be an issue with Tailwind or this module (or content module imo), it would just become invalid syntax. As a workaround, you can do

```
::p{class="text-lg leading-8 text-[#dddddd]"}
::
```
