### ISSUE TITLE
WARN  [vite:css] Nested CSS was detected, but CSS nesting has not been configured correctly.

### ISSUE THREAD

**Issue by wojciech-szymanski** [nuxt-modules/tailwindcss#725]
I have configured @nuxtjs/tailwindcss 6.8.0 within Nuxt 3.7.3 project, as per docs. Linked my css files inside tailwind.css, below default tailwind imports. Top level styles and tailwind classes work, but I am not getting any nested media queries to work or more complex styles. This is the error from CLI:

```
landing:dev:  WARN  [vite:css] Nested CSS was detected, but CSS nesting has not been configured correctly.
landing:dev: Please enable a CSS nesting plugin *before* Tailwind in your configuration.
landing:dev: See how here: https://tailwindcss.com/docs/using-with-preprocessors#nesting
landing:dev: 61 |      /* Small Screen */
landing:dev: 62 |      @for $i from 1 to 4 {
landing:dev: 63 |        .tag:nth-of-type($i) {
landing:dev:    |         ^
landing:dev: 64 |          @apply flex;
landing:dev: 65 |        } (x5)
```

Is that a bug or configuration problem?

**Comment by ineshbose** [comment]
Hi, thanks for opening an issue on this repo; apologies for not getting to this earlier.

From the looks of it, "`@for $i from 1 to 4`" - the whole segment seems to be similar to SASS syntax, while Tailwind works best with PostCSS - are you sure you're using it correctly? You may configure postcss to have additional plugins to have SASS-like features though. Let me know.
