### ISSUE TITLE
Additional CSS files to load with the viewer for css variables & viewer customization

### ISSUE THREAD

**Issue by MatanelGordon** [nuxt-modules/tailwindcss#727]
### Is your feature request related to a problem? Please describe.
I'm currently working on syncing `primevue's` theme with tailwind. `Primevue` exports its entire color palette via  css variables, so all I need to do in my Tailwind Configuration is to set `theme.colors` to be overridden by primevue's css variables. However, when i open the viewer, it fails to show me the new colors since it doesn't have those variables set. 

### Describe the solution you'd like
it would be great if you could add a `cssFiles` option for this module so I could add primevue's css files (with the variables) and hence show the colors correctly. 

In addition, it's a great chance to allow css modification to the viewer and better customization. 

### Describe alternatives you've considered
Disabling the viewer works because it can't really show the color palette properly

### Additional context
Here's the not working version of the viewer after syncing `primevue` with `tailwindcss`:

<img width="1100" alt="image" src="https://github.com/nuxt-modules/tailwindcss/assets/72258277/4a3d03fb-3f93-450e-a283-3887e92e70f5">

**Comment by ineshbose** [comment]
Hi, thanks for opening an issue on this repository.

One of my Nuxt applications also uses PrimeVue along with this module, and I've worked intensely in getting the two integrated, so I'd quite like to look into this. I haven't had the chance to look at PrimeVue's latest update of allowing syncing with Tailwind (but it probably means my hours of writing custom PCSS to respect Tailwind have been made redundant), but I'm trying to understand your feature idea of `cssFiles`. From what I understand, Tailwind has an entry CSS file that you can specify in the configuration... within that, if you'd like to import PrimeVue's CSS (and as a layer), or use a Tailwind plugin, that would be sufficient if I'm not wrong? Perhaps you could provide a code snippet of what you'd mean. 🙂

**Comment by MatanelGordon** [comment]
Adding the css file through tailwind configuration is a great idea! thanks
