### ISSUE TITLE
[Security Vulnerability] Update dependency `postcss` to `8.4.31` or higher

### ISSUE THREAD

**Issue by madebyfabian** [nuxt-modules/tailwindcss#734]
This module currently uses a `postcss` version with a moderate security vulnerability. Got the warning from dependabot in my project.

See: https://github.com/advisories/GHSA-7fh5-64p2-3v2j

### Version
@nuxtjs/tailwindcss: ^6.8.0
nuxt: 3.7.4

### What is Expected?
Upgrade to at least `8.4.31` to fix.

### What is actually happening?
Security Vulnerability due to outdated package

**Comment by ineshbose** [comment]
Updating dependencies and creating a release soon. Meanwhile, please feel free to use `"overrides"` in your `package.json`.

**Comment by ineshbose** [comment]
Released v6.8.1 🙂

**Comment by madebyfabian** [comment]
@ineshbose Thank you! 🙏🏻
