### ISSUE TITLE
Creating a new color in tailwind.config.js with 'newcolor: defaultTheme.colors.sky' is not working

### ISSUE THREAD

**Issue by StefanFlaschko** [nuxt-modules/tailwindcss#737]
### Version
@nuxtjs/tailwindcss:  "^6.8.0"
nuxt: "^3.8.0"

### Reproduction Link
https://codesandbox.io/p/sandbox/affectionate-haze-l4ckjx

### Steps to reproduce
In the tailwind.config.js add:
`
import defaultTheme from "tailwindcss/defaultTheme";
//and
theme: {
    extend: {
      colors: {
        newcolor: defaultTheme.colors.sky,        
      }
    }
  },
`

in index.vue try to use it like:
`
<div class="text-newcolor-400">
      Here should be a new color
</div>
`

### What is Expected?
The color sky-400 should be applied to the element.

### What is actually happening?
No color is applied

**Comment by ineshbose** [comment]
Duplicate #659 

Please refer https://tailwindcss.com/docs/customizing-colors#using-the-default-colors to make better use of Tailwind's default colors provided as `tailwindcss/colors`.

**Comment by StefanFlaschko** [comment]
` import colors from 'tailwindcss/colors'` fixed it for me. Thanks. 
Would be great to add this to the docs.
