### ISSUE TITLE
Svg rendering 

### ISSUE THREAD

**Issue by anthonyfranc** [nuxt-modules/tailwindcss#749]
### Version
@nuxtjs/tailwindcss: 6.9.0 or 6.9.1
nuxt: 3.8

### Steps to reproduce
Package above 6.8.1 fail to render SVG. 

### What is Expected?
Rendering of SVG

**Comment by ineshbose** [comment]
Can you provide some context and a replication of the issue please?

6.9.0 onwards had some changes in content configuration - maybe there's a difference there if you want to investigate and see what may have been left out or missed?

**Comment by ineshbose** [comment]
Please check 6.9.2

**Comment by anthonyfranc** [comment]
Can confirmed it's fixed using 6.9.3, thanks!
