### ISSUE TITLE
Logical properties are not working with Nuxt 2

### ISSUE THREAD

**Issue by basemkhirat** [nuxt-modules/tailwindcss#760]
### Version
@nuxtjs/tailwindcss: 6.9.4
nuxt: 2.17.2

The issue is exist with nuxt2 but works fine in nuxt3.

### Reproduction Link

https://codesandbox.io/p/sandbox/hungry-bird-k2r8qr

### Steps to reproduce

To reproduce the issue, you can generate a fresh installation of Nuxt2, then use Tailwindcss as the UI Framwork.

### What is Expected?

In TailwindCSS v3, adding the class `ms-10`should generate the CSS rule `margin-inline-start: 2.5rem` 

[using-logical-properties](https://tailwindcss.com/docs/margin#using-logical-properties)

### What is actually happening?

When I add the class`ms-10`, the CSS rule `margin-left: 2.5rem` will be rendered!

**Comment by basemkhirat** [comment]
This issue related to nuxt.

Fixed by updating `nuxt.config.js`

```
 build: {
   postcss: {
     preset: {
       stage: 3,
     },
   },
 }
```

https://github.com/nuxt/nuxt/issues/8387

**Comment by ineshbose** [comment]
Thanks for researching into it and documenting the issue for future reference. In this case, I'm closing the issue as it's not in module scope.
