### ISSUE TITLE
Add option to show current breakpoint name

### ISSUE THREAD

**Issue by iBobik** [nuxt-modules/tailwindcss#772]
### Is your feature request related to a problem? Please describe.
When designing responsive it is handy to know which breakpoint applies currently and I does not remember the values.

### Describe the solution you'd like
Add tile to the Nuxt Devtools Button (that what is floating constantly on the site in dev mode).

### Describe alternatives you've considered
Add it manually. Some examples:
https://gist.github.com/jonsugar/6bce22bd7d3673294caad36046c2b7cb

**Comment by ineshbose** [comment]
Thanks for opening an issue.

Couple of things I can point you to, for this.

1. VueUse has `useBreakpoints().current` property to see what breakpoints are active - https://vueuse.org/core/useBreakpoints (last element is the most relevant)
2. The element can be added to the config viewer, if you create a feature request - https://github.com/rogden/tailwind-config-viewer

Rest, if this needs to be come from the module as default behaviour, we'll need to see the demand for this.
