### ISSUE TITLE
is it possiable to set preflight: false in nuxt.config?

### ISSUE THREAD

**Issue by MikeLee0358** [nuxt-modules/tailwindcss#777]
thank you for your great work! I encountered some problem, I want to turn off preflight setting

- goal
want to set preflight: false in nuxt3/ nuxt.config

- what did i do
  // nuxt.config.ts
  export default defineNuxtConfig({
    devtools: { enabled: true },
    modules: ['@pinia/nuxt', '@nuxtjs/tailwindcss'],
    tailwindcss: {
      preflight: false
    },
  })

**Comment by ineshbose** [comment]
You should be able to set preflight to false like this:

```ts
export default defineNuxtConfig({
  devtools: { enabled: true },
  modules: ['@pinia/nuxt', '@nuxtjs/tailwindcss'],
  tailwindcss: {
    config: {
      corePlugins: { preflight: false }
    }
  },
})
```

Let me know if that works for you.
