### ISSUE TITLE
nuxt2-playground  【TButton】not working

### ISSUE THREAD

**Issue by soulmate126** [nuxt-modules/tailwindcss#780]
Nuxt-playground's `TButton` doesn't work out of the box. I haven't made any configuration changes.

**Comment by ineshbose** [comment]
I'm seeing the same behaviour - but just to confirm, your Nuxt 2 app is unaffected, correct?

**Comment by soulmate126** [comment]
What I mean is, this package doesn't work in `nuxt2`

**Comment by ineshbose** [comment]
Do you know the last working version?

**Comment by ineshbose** [comment]
It seems to be working if you try on https://stackblitz.com/github/nuxt/starter/tree/v2-stackblitz (both `latest` and `nightly`). It just seems to be the repository playground misbehaving which I need to investigate.

**Comment by soulmate126** [comment]
Sorry, it might be an issue with `nuxt bridge`.  It works fine in Nuxt 2.
https://stackblitz.com/edit/github-edkxhs
