### ISSUE TITLE
Missing release including latest Tailwind version

### ISSUE THREAD

**Issue by ChrizzDF** [nuxt-modules/tailwindcss#781]
Hi guys!
First of all: Thanks for maintaining! 🙏 

I just saw that the bump with the newest Tailwind version has been merged:
https://github.com/nuxt-modules/tailwindcss/pull/779

But there's no release out yet, including these changes.

When do you guys plan to do this?

**Comment by ineshbose** [comment]
Hi, thanks for opening an issue.

We have a nightly release out for Tailwind 3.4, but we're working on 6.10.2 (we've found a minor issue we're trying to fix and also update other dependencies) to arrive ASAP; should be aimed for 26th December.

**Comment by ineshbose** [comment]
6.10.2 released - sorry for the delay 🙂
