### ISSUE TITLE
Duplicated baseURL in viewerUrl

### ISSUE THREAD

**Issue by CLDXiang** [nuxt-modules/tailwindcss#782]
### Version
@nuxtjs/tailwindcss: v6.10.1
nuxt: v3.8.2

### Steps to reproduce

1. Create a new nuxt project
2. Setup @nuxt/tailwindcss
3. Add `app.baseURL: '/subpath/'` in `nuxt.config`
4. Run `nuxt dev`

### What is Expected?

The viewer path should be: `http://localhost:3000/subpath/_tailwind/`

### What is actually happening?

A viewerPath with dup baseURL was given: `http://localhost:3000/subpath/subpath/_tailwind/`

<img width="853" alt="image" src="https://github.com/nuxt-modules/tailwindcss/assets/23160486/d996e0be-6270-4909-b377-ec3d46e5fa9d">

**Comment by ineshbose** [comment]
Will be fixed on nightly release. 🙂
