### ISSUE TITLE
nuxt.hook('tailwindcss:config') hooks dont working

### ISSUE THREAD

**Issue by productdevbook** [nuxt-modules/tailwindcss#785]
The issue was discussed here. The solution is there. https://github.com/nuxt/nuxt/issues/24943

solution: https://github.com/nuxt/nuxt/issues/24943#issuecomment-1872004595

**Comment by ineshbose** [comment]
Is this not because you have registered the hook after the module?
https://github.com/nuxt/nuxt/issues/24943#issuecomment-1871849146

Using `modules:done` is a way but I don't think it'll give any benefit, but delay creating the resolved config and templates.

**Comment by productdevbook** [comment]
https://github.com/oku-ui/pergel/blob/ac6eb12b6247c59d98a73460168309195c07c96b/packages/nuxt/src/runtime/modules/ui/index.ts#L277-L282

I am using it here in my own module. and console.log absolutely cannot see

**Comment by ineshbose** [comment]
Move it before line 176 and give it a go?

**Comment by productdevbook** [comment]
> Move it before line 176 and give it a go?

yes, it is working. But why ?

cc: @danielroe

**Comment by ineshbose** [comment]
> > Move it before line 176 and give it a go?
> 
> yes, it is working. ❤️  But why ?

Yes, same thing as the module ordering. You first register the hook, and then you install module that'll call the hook(s). 🙂
