### ISSUE TITLE
The following docs reference includes code that no longer works.

### ISSUE THREAD

**Issue by pmnzt** [nuxt-modules/tailwindcss#786]
[reference](https://tailwindcss.nuxtjs.org/tailwind/config#tailwindconfig).

The following code 
```js
import defaultTheme from 'tailwindcss/defaultTheme'

export default {
  theme: {
    extend: {
      colors: {
        primary: defaultTheme.colors.green
      }
    }
  }
}
```

no longer works the output of defaultTheme.colors.green is undefined.

after researching the tailwind docs i tried this instead and it worked.
```js
 import colors from 'tailwindcss/colors'

export default {
  theme: {
    extend: {
      colors: {
        primary: colors.green
      }
    }
  }
}
```

**Comment by manniL** [comment]
@pmnzt PR to the docs welcome!

**Comment by pmnzt** [comment]
@manniL 
> @pmnzt PR to the docs welcome!

Sorry for being late!
Here is the PR #788
