### ISSUE TITLE
Version 6.11.x throws a compatability error when Nuxt bridge is not used

### ISSUE THREAD

**Issue by cjpearson** [nuxt-modules/tailwindcss#797]
### Version
@nuxtjs/tailwindcss: 6.11.0 (Or newer)
nuxt: 2.17.3

### Steps to reproduce

Upgrade to version 6.11.0 of `@nuxtjs/tailwindcss` in a Nuxt 2 non-bridge project and run the build.

### What is Expected?

Build successfully without warnings or errors

### What is actually happening?

There is now a warning that Nuxt bridge is required. 

```
 ERROR  Nuxt compatibility issues found:                                                                                                                      5:50:28 PM
 - [bridge] Nuxt bridge is required

  - [bridge] Nuxt bridge is required
  at assertNuxtCompatibility (node_modules/@nuxtjs/tailwindcss/node_modules/@nuxt/kit/dist/index.mjs:76:11)
```

The application still appears to work fine. Could this be a false positive?

**Comment by cjpearson** [comment]
Looks like it might be related to #784. Maybe we could add an `isNuxt2()` check around here? https://github.com/nuxt-modules/tailwindcss/blob/8280b27645bd9d3882b0726bfab323369990ce3d/src/module.ts#L157

**Comment by ineshbose** [comment]
Thanks for reporting - I noticed this too. I assume the code still considers editorSupport to be set to true if isNuxt2 (need to safeguard that). PR is welcome 🙂

**Comment by ineshbose** [comment]
Should be fixed in [nightly](https://tailwindcss.nuxtjs.org/getting-started/installation#nightly-releases) if you'd like to try and confirm; will release 6.11.3 then.

**Comment by cjpearson** [comment]
Just tried it and it seems to work well. Thanks for the quick fix!
