### ISSUE TITLE
Why are unused styles not cleared?

### ISSUE THREAD

**Issue by champ7champ** [nuxt-modules/tailwindcss#803]
nuxt.config

<img width="323" alt="image" src="https://github.com/nuxt-modules/tailwindcss/assets/81758691/457b5e22-215a-4c70-b84f-0ac2c6ac7827">

<img width="404" alt="image" src="https://github.com/nuxt-modules/tailwindcss/assets/81758691/95efeb7d-7512-48ad-acfc-06f663092c63">
tailwind.config.js

**Comment by ineshbose** [comment]
You need not do any of this configuration by yourself as this module adds the paths properly resolved.

You should share a reproduction to provide context of what styles you're talking about that is unused.

**Comment by champ7champ** [comment]
> You need not do any of this configuration by yourself as this module adds the paths properly resolved.
> 
> You should share a reproduction to provide context of what styles you're talking about that is unused.

I need tailwind to generate only those styles that I use in the project, but it rolls out absolutely all the styles for me

**Comment by ineshbose** [comment]
Again, please provide a reproduction on this - it may be due to your CSS directives, content detections, or autoimports, etc.

**Comment by champ7champ** [comment]
Nuxt 3 

<img width="968" alt="image" src="https://github.com/nuxt-modules/tailwindcss/assets/81758691/790bbb4a-0b70-4317-9289-ba3bd5fcf43f">

<img width="420" alt="image" src="https://github.com/nuxt-modules/tailwindcss/assets/81758691/84e87fe3-2bff-4157-a002-f34c37edc3e1">


<img width="807" alt="image" src="https://github.com/nuxt-modules/tailwindcss/assets/81758691/e6f07b80-9a9b-439b-b703-19833beb5ff8">

**Comment by ineshbose** [comment]
I think what you're willing to do is - https://github.com/nuxt/ui/issues/877#issuecomment-1825437924
