### ISSUE TITLE
Scope tailwind to certain parts of a nuxt app

### ISSUE THREAD

**Issue by woldtwerk** [nuxt-modules/tailwindcss#804]
Use case:
Admin Panel with nuxt ui and public pages without tailwind or different tailwind config.

I was expecting that
```ts
cssPath: false
```
and manually importing the css file in a page or layout would work.  It is still treated as global css though.

How do scope tailwind to certain parts of my application?

**Comment by ineshbose** [comment]
Its a good question and the Tailwind community still wonders about how to best go about it, but the intention of Tailwind utility classes are to keep them global and not scoped - it destroys one of the purposes of Tailwind.

https://tailwindcss.com/docs/functions-and-directives#using-apply-with-per-component-css

The above link talks about it a bit so it should be understandable.

**Comment by woldtwerk** [comment]
That's not what I meant. After further testing the issue is not related to this module, but nuxt itself

**Comment by ineshbose** [comment]
> That's not what I meant. After further testing the issue is not related to this module, but nuxt itself

I wouldn't call it an issue for Nuxt either. Nuxt/Vite would preprocess whatever you do with PostCSS, it's just Tailwind isn't designed for that as far as I know. If you're aware of any mechanisms that help you with this in alternative frameworks, feel free to link so we can brainstorm on what may be possible for this scenario in Nuxt.
