### ISSUE TITLE
Project install fails after updating past version 6.10.2

### ISSUE THREAD

**Issue by gal-cernilogar** [nuxt-modules/tailwindcss#807]
### Version
@nuxtjs/tailwindcss: v6.10.2
nuxt: v3.9.3

### Steps to reproduce
1. Disable/uninstall pnpm (the problem exists in a project setup, where npm is the only package manager)
2. Start with a project using module v6.10.1 or less with the corresponding package-lock.json
3. Make sure to remove all git ignored local folders, including .nuxt and node_modules or anything that might contain cache of previous installations
4. Update the module to v6.10.2 and install dependencies with `npm install`

### What is Expected?
Project dependencies should install.

### What is actually happening?
The install fails with:
```shell
npm ERR! code 127
npm ERR! path /*****/node_modules/@nuxtjs/tailwindcss
npm ERR! command failed
npm ERR! command sh -c pnpm dev:prepare
npm ERR! sh: pnpm: command not found
```

The issue was discovered when hunting for a specific release that caused some layout breaks after updating to the latest version.
It seems that the install does not fail without removing the folders beforehand as described in the steps.

Not sure, if this is the cause of the issue but I suspect it has something to do with [these changes](https://github.com/nuxt-modules/tailwindcss/compare/v6.10.1...v6.10.2#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R31)

**Comment by ineshbose** [comment]
Please update to the latest version - it should resolve this.
