### ISSUE TITLE
Custom background color is not displayed in published versions

### ISSUE THREAD

**Issue by bbhxwl** [nuxt-modules/tailwindcss#809]
### Version
@nuxtjs/tailwindcss:   ^6.11.2
nuxt: ^3.10.2

Set the background color, which can be displayed in dev mode, but cannot be displayed in the official version released
Can only  npm run dev, cannot  npm run build

```
class="item flex flex-col px-2 py-1 bg-[#29B1C7] rounded"
```

**Comment by bbhxwl** [comment]
The reason is because nuxt purge is used, why is it not compatible?

**Comment by ineshbose** [comment]
Answered in #812 👍
