### ISSUE TITLE
How to cancel the styles of h1~h6 and prohibit modification?

### ISSUE THREAD

**Issue by bbhxwl** [nuxt-modules/tailwindcss#812]
How to cancel the styles of h1~h6 and prohibit modification?

![image](https://github.com/nuxt-modules/tailwindcss/assets/26525599/e520f639-eb8c-4da1-a322-8a5a173eda5f)

**Comment by ineshbose** [comment]
This is part of the Tailwind CSS preflight (refer https://tailwindcss.com/docs/preflight#headings-are-unstyled) - you can set styles like `h1 { all: unset; }` but it's not recommended; you can either [disable preflight](https://tailwindcss.com/docs/preflight#disabling-preflight) or look into the [typography plugin](https://tailwindcss.com/docs/typography-plugin).
