### ISSUE TITLE
Problem differentiating focus state from focus-visible.

### ISSUE THREAD

**Issue by mrc-bsllt** [nuxt-modules/tailwindcss#814]
### Version
@nuxtjs/tailwindcss: v6.11.4
nuxt: v3.10.1 (but also v3.10.3)

### Reproduction Link
https://stackblitz.com/edit/nuxt-starter-dxz9qq?file=app.vue

### Steps to reproduce
Click with the mouse inside the input, thus activating the focus state. Use the tab key to highlight the input, activating the focus-visible state. The style is always the same.

### What is Expected?
I expect the style to be different. With the classes I used at focus there should be no outline, whereas at focus-visible there is.

### What is actually happening?
The focus-visible state overwrites the focus state.

**Comment by ineshbose** [comment]
So just confirming that you want these states to be different:

| On click | On tab |
| --------- | ------- |
| ![image](https://github.com/nuxt-modules/tailwindcss/assets/56732164/1774edf2-1912-4751-b787-44c5ffe3f322) | ![image](https://github.com/nuxt-modules/tailwindcss/assets/56732164/7d7e2d1f-577d-4319-936b-cbda2b735288) |

This question is more (Tailwind) CSS related...

Read: https://stackoverflow.com/questions/75365592/tailwindcss-how-to-focus-within-and-focus-visible-at-the-same-time, https://github.com/tailwindlabs/tailwindcss/discussions/10507, https://stackoverflow.com/a/43283017/12938670, https://stackoverflow.com/a/36582442/12938670

You could use `[&:has(:focus-visible)]`, have a wrapper div with `focus-within`, and/or use window events to see if the target is the input element and add styles accordingly.
