### ISSUE TITLE
How to override default tailwind.css?

### ISSUE THREAD

**Issue by avxkim** [nuxt-modules/tailwindcss#822]
I want to override `@layers`, `@components` inside tailwind.css, but i've checked documentation, and found no information on how to achieve that.

**Comment by ineshbose** [comment]
You could use a Tailwind plugin, or add your own `assets/css/tailwind.css` file for control:

```css
@import 'tailwindcss/base';
@import 'tailwindcss/components';
@import 'tailwindcss/utilities';

@layer components {
}
```

**Comment by ineshbose** [comment]
Yes! You can do both; the plugin approach would be preferable due to the JS/CSS scoping.

https://tailwindcss.com/docs/plugins#adding-components

**Comment by avxkim** [comment]
i see now, thanks. As i understood, we can just add our components using TW plugin inside tailwind.config.ts
