### ISSUE TITLE
Attributify mode

### ISSUE THREAD

**Issue by kleinpetr** [nuxt-modules/tailwindcss#823]
Hi,

I am wondering if there is any possibility to use the attributify mode as it's on unocss 
https://unocss.dev/presets/attributify

Thanks for the information.

**Comment by ineshbose** [comment]
Thanks for opening an issue on this repository - I believe this feature may be relevant to Tailwind CSS core. May I direct you to the discussion for the same: https://github.com/tailwindlabs/tailwindcss/discussions/5536
