### ISSUE TITLE
`tw` autocomplete utility regex improvements

### ISSUE THREAD

**Issue by DamianGlowala** [nuxt-modules/tailwindcss#824]
E.g. the function variant would be:

```
"tw\\(\\s*('(.*?)'|\"(.*?)\")\\s*\\)"
```

Noticed the first and last class do not have IntelliSense enabled with the above regex though and I am not sure why.

**Comment by ineshbose** [comment]
You're quite right - I'm surprised this wasn't reported earlier, but I've felt that the autocomplete utility isn't used much by developers. PR welcome! 🙂
