### ISSUE TITLE
call `tailwindcss:config` hook after all modules are initialised

### ISSUE THREAD

**Issue by danielroe** [nuxt-modules/tailwindcss#826]
At the moment, `tailwindcss:config` is called synchronously when this module runs, meaning other modules which hope to use tailwindcss or modify its configuration must be registered _before_ it.

However, dependencies between modules aren't ideal. Instead, we should register a hook in `modules:done` that finally calls `tailwindcss:config`. Alternatively, we could also call `tailwindcss:config` directly in `getContents` of a template.

**Comment by ineshbose** [comment]
I'm looking to address this in #818 as that is a complete rewrite of loading the config. 👍
