### ISSUE TITLE
Cannot find module "tailwindcss" when installing with pnpm

### ISSUE THREAD

**Issue by MalachiDraven** [nuxt-modules/tailwindcss#849]
Following the documentation, installing this module with pnpm as such: `pnpm i -D @nuxtjs/tailwindcss
`. Setting up `tailwind.config.ts` as:
```ts
import type { Config } from "tailwindcss"
import colors from "tailwindcss/colors"

export default <Partial<Config>>{
    theme: {
        extend: {
            colors: {
                primary: colors.green,
            },
        },
    },
}
```

Getting the following TS errors:
`Cannot find module 'tailwindcss' or its corresponding type declarations.ts(2307)`
`Cannot find module 'tailwindcss/colors' or its corresponding type declarations.ts(2307)`

These errors don't occur if using npm or yarn, only with pnpm. I'm new to using pnpm, so did I do something wrong or miss a step?

**Comment by ineshbose** [comment]
I think something may be specific to your project/editor; it's difficult to say without looking at the project / getting entire context, but the setup for that is likely outside the scope of this module. You can try using `shamefully-hoist` with pnpm (but it shouldn't be required). 🙂
