### ISSUE TITLE
Prop to bind a class to an element doesn't apply style

### ISSUE THREAD

**Issue by hungify** [nuxt-modules/tailwindcss#858]
### Environment

- Operating System: Darwin
- Node Version:     v20.11.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  bun@1.1.10
- Builder:          -
- User Config:      devtools, modules, components
- Runtime Modules:  @nuxt/eslint@0.3.13, @nuxtjs/tailwindcss@6.12.0, @vueuse/nuxt@10.10.0, nuxt-icon@0.6.10, @nuxt/image@1.7.0
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-jmgc7d?file=components%2FBadge.vue

### Describe the bug

1. Create a component with a prop that is a string 
```ts
const colorByType = {
  red: 'red',
  green: 'green',
  blue: 'blue',
} as const;

interface Props {
  type: keyof typeof colorByType;
  size?: 'small' | 'medium' | 'large';
  radius?: 'md' | 'lg' | 'xl';
}

const props = withDefaults(defineProps<Props>(), {
  size: 'medium',
  radius: 'md',
});
```
3. Use the prop to bind a class to an element
```vue
<span
    :class="{
      [`bg-${color}-500`]: true,
      [`text-${color}-100`]: true,
      [`px-1 py-1`]: size === 'small',
      [`px-2 py-1`]: size === 'medium',
      [`px-3 py-1`]: size === 'large',
      [`rounded-${radius}`]: radius,
    }"
  >
    <slot />
  </span>
```
3. Look at the element in the browser
![CleanShot 2024-06-08 at 12 19 31@2x](https://github.com/nuxt-modules/tailwindcss/assets/78008509/dc330c78-6dfa-4b72-b962-a6c73bf3ce32)

The class displays the element but the style doesn't apply

But when I create another element with the same class it works, after that the style applies to the previous element too.

```vue
// new and remove later
<div class="bg-red-500 text-red-100 px-2 py-1 rounded-md" />

<span
    :class="{
      [`bg-${color}-500`]: true,
      [`text-${color}-100`]: true,
      [`px-1 py-1`]: size === 'small',
      [`px-2 py-1`]: size === 'medium',
      [`px-3 py-1`]: size === 'large',
      [`rounded-${radius}`]: radius,
    }"
  >
    <slot />
  </span>
```

**Comment by ineshbose** [comment]
I think you're looking to use dynamic classes that the Tailwind content detection cannot extract. Read https://tailwindcss.com/docs/content-configuration#dynamic-class-names. You may need to provide entire classes, or configure safelist. 🙂

**Comment by hungify** [comment]
@ineshbose Oops, many thanks!
I have to take some time to dive deep into Tailwind CSS.
