### ISSUE TITLE
Change default config file location for Nuxt 4?

### ISSUE THREAD

**Issue by AnotiaWang** [nuxt-modules/tailwindcss#862]
Now that [Nuxt 4](https://nuxt.com/docs/getting-started/upgrade#migrating-to-nuxt-4) is on the horizon, according to the [new directory structure](https://github.com/nuxt/nuxt/issues/26444), should we move Tailwind config to the `app` folder, considering that Tailwind CSS is a frontend thing?

The [doc](https://tailwindcss.nuxtjs.org/getting-started/installation#tailwind-files) says this module looks for config file under the root path by default. Should this be changed as well? Or I have to update Nuxt config if I want to try out features of Nuxt 4:

```ts
export default defineNuxtConfig({
  // ...
  future: {
    compatibilityVersion: 4
  },
  tailwindcss: {
    configPath: './app/tailwind.config'
  },
})
```

**Comment by ineshbose** [comment]
Hi, thanks for opening an issue on this repository. It's certainly interesting to think where should the `tailwind.config` live. While you can argue that it's a frontend thing, it's also a build-time PostCSS thing, so I would think that the config file should live at the same level where you may have `{nuxt,vite,postcss}.config`. I feel (rc)config files are typically in root, and `app` is a Nuxt-app concept for pages, plugins, etc. There's also the `.config` proposal and we're definitely considering that so it should be even clearer, so feel free to chip into #808 and #790. 🙂
