### ISSUE TITLE
[6.12] Cannot read properties of undefined (reading 'some') 

### ISSUE THREAD

**Issue by fasenderos** [nuxt-modules/tailwindcss#865]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.14.0
- Nuxt Version:     3.6.5
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  pnpm@9.4.0
- Builder:          -
- User Config:      devtools, modules
- Runtime Modules:  @nuxtjs/tailwindcss@6.12.0
- Build Modules:    -
------------------------------

### Describe the bug

In a newly created Nuxt.js project, running `nuxt dev` fails after adding `@nuxtjs/tailwindcss` to `nuxt.config.ts`. The error points to this line of code.
https://github.com/nuxt-modules/tailwindcss/blob/a0d75998f1c12ea4fbb7cefefe0c90c1cdd99023/src/context.ts#L190

Here is my `nuxt.config.ts`
```
export default defineNuxtConfig({
  devtools: { enabled: true },
  modules: ['@nuxtjs/tailwindcss'],
});
```

### Additional context

The project is a `pnpm` monorepo where all packages are inside the folder `apps` and `@nuxtjs/tailwindcss` has been installed with `pnpm --filter=@project/nuxtjs -D -E @nuxtjs/tailwindcss`

**Comment by ineshbose** [comment]
Can you test [nightly](https://tailwindcss.nuxtjs.org/getting-started/installation#opting-into-the-nightly-channel) and confirm if it is solved?
