### ISSUE TITLE
Tailwind CSS is included twice in the project

### ISSUE THREAD

**Issue by abocsan-plenty** [nuxt-modules/tailwindcss#880]
### Environment

- Operating System: Darwin
- Node Version:     v20.11.1
- Nuxt Version:     3.12.2
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  yarn@3.6.4
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
- nuxtjs/tailwindcss Version: 6.12.0

### Reproduction

https://github.com/plentymarkets/plentyshop-pwa

Please refer to additional context section for what it looks like.

### Describe the bug

I've noticed that the Tailwind CSS framework is being included twice in my project when using this package. This duplication can cause unexpected behavior and increase the load time of the project.

### Additional context

https://plentyshop.plentymarkets.com/

<img width="1467" alt="Screenshot 2024-07-25 at 09 46 25" src="https://github.com/user-attachments/assets/07844ddb-e968-4371-a032-77b509adef66">

**Comment by ineshbose** [comment]
Hey! Thanks for opening an issue.

I see in your `nuxt.config`, you have provided a path to `style.scss` in `css`, and that file calls the `@tailwind` directives. The module isn't aware that you already have a CSS file plugged into Nuxt that is also using the tailwind directives, so it will add its own stylesheet too. You may want to either 1) remove tailwind directives from `style.scss`, 2) use `assets/css/tailwind.css` instead, or 3) set `tailwindcss.cssPath` to `false` in `nuxt.config`.

Let me know! 😄
