### ISSUE TITLE
Current Breakpoint Indicator in DevTools Module

### ISSUE THREAD

**Issue by maclong9** [nuxt-modules/tailwindcss#882]
### Describe the feature

We can currently view the list of breakpoints under the __Screens__ section of the tailwind viewer, it would be amazing if we could have the current active breakpoint within this tab as well. 

This would help for quick debugging and breakpoint applications. I'd be more than happy to implement this if you guys are okay with that! [Similar tools already exist](https://github.com/Hounddd/tailwindcss-breakpoints-inspector) however it would be great to have it integrated into the Vue DevTools!

Thanks for reading,

Mac

### Additional information

- [x] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

**Comment by maclong9** [comment]
I'll get started on a simple implementation later this evening and setup a pull request.

**Comment by ineshbose** [comment]
Hey, thanks for opening an issue and sharing this suggestion!

The config viewer would be an upstream dependency - https://github.com/rogden/tailwind-config-viewer which I am seeing has a related issue for this - https://github.com/rogden/tailwind-config-viewer/issues/50

Do you think it would be better to create a PR there?

**Comment by maclong9** [comment]
Good shout, I didn’t realise the viewer had a different dependency, I’ll move this over to there.
