### ISSUE TITLE
Tailwind Css hot reloaded on every change in every pages

### ISSUE THREAD

**Issue by aminshafieed** [nuxt-modules/tailwindcss#890]
Hi. i'm using nuxt/tailwindcss in my project. the problem is that even if i change a text, tailwindcss.css hot reloaded too and it take too long(more than 10 second).
how can i disable tailwind hot reload in nuxt 3

![Screenshot from 2024-08-16 16-55-41](https://github.com/user-attachments/assets/be91ab89-a12b-4258-887f-395f9219c680)

**Comment by ineshbose** [comment]
Hi, thanks for opening an issue on this repository. I'll provide you with an explanation on why this happens -

1. Tailwind CSS is a PostCSS plugin in your (Vite/Webpack/etc) application.
2. Tailwind CSS has a content detection system to only provide you with classes that you use in your source-code.
3. In that, you may be holding the classnames as strings in variables, passing them directly in the HTML, etc - all in all, it tries to do a quick search for the classes in your source files.
4. When you change code, it could mean that the character you provide may be to specify/remove a classname to Tailwind, so HMR triggers.

Tailwind v4 may be looking to address some performances or mechanisms on this, but the HMR should not take so long in your project, so this may be some configuration causing a bottleneck (perhaps you would like to share your `{nuxt,tailwind}.config`). A minor related issue to page reloads on HMR is here that is under investigation - https://github.com/nuxt-modules/tailwindcss/issues/877.

> how can i disable tailwind hot reload in nuxt 3

If you switch to [nightly release](https://tailwindcss.nuxtjs.org/getting-started/installation#nightly-releases), you can use the [`disableHMR` option](https://github.com/nuxt-modules/tailwindcss/blob/1be549707da8c5c395b98ae85060d9ae2a6281af/src/types.ts#L146). I hope this helps. 🙂
