### ISSUE TITLE
How to support the tailwind `Config` type with PNPM?

### ISSUE THREAD

**Issue by itsmelouis** [nuxt-modules/tailwindcss#897]
Hello! I just started a Nuxt app with those following specs: 

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.20.4
- Nuxt Version:     3.13.2
- CLI Version:      3.13.2
- Nitro Version:    2.9.7
- Package Manager:  pnpm@9.10.0
- Builder:          -
- User Config:      compatibilityDate, modules, devtools, future
- Runtime Modules:  @nuxtjs/tailwindcss@6.12.1, radix-vue/nuxt, @nuxt/icon@1.5.1
- Build Modules:    -
------------------------------

I created a tailwind.config.ts file to extend my own theme but here's the bummer:

![image](https://github.com/user-attachments/assets/acb1760e-12f0-42f3-bf15-9c47a9b18736)

I can't have the type support for tailwindcss related package in the config :/

However, using NPM works fine. 

Do you have any ideas why?

**Comment by MuhammadM1998** [comment]
It's working a s expected for me and I'm using pnpm. Maybe try adding `shamefully-hoist=true` to your `.npmrc`?

![Screenshot 2024-09-26 140428](https://github.com/user-attachments/assets/5f70b5a2-cf45-4085-ba07-decd8b7037e8)

**Comment by GreenmeisterDavid** [comment]
Having the same issue, I also use PNPM. I'm not familiar with `shamefully-hoist=true`, but I tried adding it to .npmrc but issue persisted.

**Comment by MuhammadM1998** [comment]
@GreenmeisterDavid Did you re-install the dependencies after adding `shamefully-hoist=true`?. Try removing your node_modules and reinstalling.

**Comment by ineshbose** [comment]
Thanks for opening an issue (and to @MuhammadM1998 for supporting).

This is usually IDE/environment specific, but I believe `shamefully-hoist=true` shouldn't be required anymore.. something to do with the local TypeScript server/configuration. Would you be able to provide more environment context about your editor possibly? Closing this, but we can continue discussion!
