### ISSUE TITLE
install with nuxi isn't dev dependency

### ISSUE THREAD

**Issue by flomero** [nuxt-modules/tailwindcss#905]
### Environment

- Operating System: Linux
- Node Version:     v22.9.0
- Nuxt Version:     3.13.2
- CLI Version:      3.14.0
- Nitro Version:    2.9.7
- Package Manager:  yarn@1.22.22
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Describe the bug

if you use `npx nuxi@latest module add tailwindcss`, as recommended [here](https://nuxt.com/modules/tailwindcss), it saves tailwind as a dependency in package.json

all other recommended ways install save it as a dev dependency (including the Tailwind Docs)

**Comment by ineshbose** [comment]
Thanks for opening an issue. It may be how nuxi is configured - but Nuxt doesn't care between dependencies or devDependencies - is it causing issues to you as a bug?

**Comment by flomero** [comment]
haven't encountered any concrete bugs. just realised that it was weird that all other places recommended to use devDependency except for the "quick install"

**Comment by ineshbose** [comment]
Yes, that is a fair point though 🙂 

Can track here - https://github.com/nuxt/cli/issues/454
