### ISSUE TITLE
Move runtime merger.js to relative path

### ISSUE THREAD

**Issue by ThomasBerneHCSE** [nuxt-modules/tailwindcss#915]
### Describe the feature

I use a docker container to run a nuxt project with tailwindcss in local in dev mode. When I try to work on my machine it doesn't find the same absolute path to the runtime merger.js in .nuxt/tailwindcss.config.cjs : 

![Image](https://github.com/user-attachments/assets/c035dab7-dc38-4e42-874f-682261edfd75)

The absolute path is different between my machine and the container. 

Can we change it to relative path please ?

![Image](https://github.com/user-attachments/assets/c07a775b-5da8-48da-ab59-b7053105e287)

Here is the error I get:
![Image](https://github.com/user-attachments/assets/8e17a347-a25d-4b99-b788-773eb0884c16)

### Additional information

- [x] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

**Comment by ineshbose** [comment]
I wonder if this could cause issues for PNPM without shamefully-hoist..

**Comment by ThomasBerneHCSE** [comment]
The path would be the same inside the node modules. That is juste the way to access node modules I want to change. The problem would be the same with pnpm.

**Comment by ThomasBerneHCSE** [comment]
@ineshbose is my explaination ok for you?

**Comment by ThomasBerneHCSE** [comment]
That would be awesome! Thank you 👍

**Comment by ThomasBerneHCSE** [comment]
@ineshbose I'm sorry to bother you again but did you managed to fix this issue? This is the only issue we have to work with docker here. Thanks again for your help and for that awesome module you built! 💯

**Comment by ThomasBerneHCSE** [comment]
@sandros94 This mustn't be a docker config issue. The path of the project inside the container is different of the path on my machine and the merge uses absolute paths. Meaning the IDE on the machine tries to locale files with absolute path as the container.

Project path inside container `/usr/src`.
Project path on the machine `/home/user/Documents/project_name`.

The IDE doesn't understand why /usr/src/{path_to_merge.js} doesn't exists on the machine.

Every other paths are relatives to the project and have 0 issues.

**Comment by sandros94** [comment]
By docker config I mean how you setup and start your dev container. It sounds like the container process (that generates files inside `.nuxt`) is aware of the host path, something that shouldn't happen at all.

Indeed the PR will help with this very case, but I would also love to get my hands on a reproduction to study if this may have more deeper issues that could leak into production.

**Comment by sandros94** [comment]
Don't get me wrong, the PR will definitely help with this very issue.

I would like to see a reproduction mainly to be sure it is about bind mount configuration and not something different that might leak into production.

Usually when you start a dev container the IDE is aware of it and should take its paths into account, unless it is a bind mount and the processes are separate

**Comment by ThomasBerneHCSE** [comment]
Is this for dependency imports in the buildDir?
=> Not only for dependencies but for every imports. Like components for example :

![Image](https://github.com/user-attachments/assets/f101d6de-22c1-4305-acd0-e7959a2bce40)

But for exports from the node_modules, nuxt does it with it's own components : 
![Image](https://github.com/user-attachments/assets/840c022f-faa3-4ed1-97ff-ffb9963712da)

I'll try out the nightly version in a couple of hours.

**Comment by ThomasBerneHCSE** [comment]
Another workaround would be to add the `.nuxt/tailwind.config.cjs` to the .gitignore. The volume wouldn't bind them. But there wouldn't be any update on the IDE of the state of tailwindcss.

**Comment by ineshbose** [comment]
> Another workaround would be to add the `.nuxt/tailwind.config.cjs` to the .gitignore. The volume wouldn't bind them. But there wouldn't be any update on the IDE of the state of tailwindcss.

Wouldn't the .nuxt directory already be in .gitignore?

**Comment by ThomasBerneHCSE** [comment]
No because in that case I couldn't have intellisence in the IDE.

**Comment by ThomasBerneHCSE** [comment]
Oh sorry. I wanted to say .dockerignore and not .gitignore.

**Comment by flavionobredev** [comment]
same for me.
