### ISSUE TITLE
Load only necessary tailwind styles for specific pages

### ISSUE THREAD

**Issue by crunchwrap89** [nuxt-modules/tailwindcss#926]
### **Problem**
Currently when building a Nuxt project with @nuxtjs/tailwindcss , the styles for all tailwind classes that are used within any components and pages will be injected to the html document in a <style> tag, even for components that are not used within the route that is being loaded. 

In other words: The <style> tag will look the same for all pages/routes.

### **Example:** 

**Example 1:**
Lets say Page A has been styled with 20 different tailwind classes, and Page B has been styled with only 10 tailwind classes.

If i navigate to Page B and inspect the document, i will see that the <style> tag contains 30 tailwind classes, when it ideally only should contain styling for 10 tailwind classes.

**Example 2:**
I have a landing page document that is served with SSR and when inspecting the document, i see that its 84kb, 
When looking closer, i see that about 60kb of that document is tailwind styles, and only 10% of that styling is actually used on the landing page.

### **Workaround**
Currently, to scope styles so that they are only loaded on necessary pages, they need to be added within a <style scoped> or <style lang="postcss" scoped"> tag.

This defeats the purpose of using tailwind, since i use tailwind to not have to jump between '<style>' and < template>' tags all the time..

### **What should i do**
What are your recommendations around this? What should i do to prevent all tailwind classes from being global & loaded to all pages?

**Comment by ineshbose** [comment]
Hey, so Tailwind utility classes are meant to be global; as you also mention that using `style scoped` defeats the purpose. Related: https://github.com/nuxt-modules/tailwindcss/issues/804#issuecomment-1929572388

https://tailwindcss.com/docs/optimizing-for-production

The above link also mentions that it's better to use `cssnano` than to split the CSS per-page or using PurgeCSS. With that said, it could still be possible using a Nitro plugin (crawl to the CSS file and update contents to the classes you detect in the page, then you're writing your own JIT/content detection code), or spawning multiple Tailwind instances in your app by importing tailwind into each `style scoped` block (and then configuring content paths) - that'll also be quite complex.. it's really a minor bit that the community hasn't optimised (publicly at least) 😅
