### ISSUE TITLE
Use default tailwind css file with inject position set to last

### ISSUE THREAD

**Issue by amini-amr** [nuxt-modules/tailwindcss#929]
### Describe the feature

I wanted to use tailwind's default css file with `injectPosition: 'last'` but that doesn't seem to be implemented. 
I could only achieve this by configuring the options like so `cssPath: ['asdf', { injectPosition: 'last' }]`. This doesn't satisfy. It isn't possible to use an empty string. using `cssPath: [false, { injectPosition: 'last' }]` also doesn't make sense but it is typed `[string | false, { injectPosition: InjectPosition }]` 

### Additional information

- [x] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

**Comment by ineshbose** [comment]
Hey 👋 

Thanks for opening an issue on this repository; that's a great observation about `cssPath`.

With that said, the idea of having `injectPosition` tied along with `cssPath` configuration is to be more *explicit* about how the CSS file is being handled. To be fair, the type should rather be `string | [string, { injectPosition }] | false`. If we provide special cases or types, it may be counter-intuitive.. so here's how I would suggest to make the change you want:

```ts
import { resolveModule } from '@nuxt/kit'

export default defineNuxtConfig({
  devtools: { enabled: true },
  modules: ['@nuxtjs/tailwindcss'],
  tailwindcss: {
    cssPath: [resolveModule('tailwindcss/tailwind.css'), { injectPosition: 'last'}]
  }
})
```

Let me know if that helps! 🙂
